README.rst, requirements-tests.txt, tests/conftest.py, tests/test_prompt.py, tests/test_render.py, voodoo/__init__.py, voodoo/cli.py
I added a `validator` argument to the `prompt` function which it passes the entered value through. If the validator raises a ValueError, the user is prompted again. The validator can mutate/change/cast the value as required, and its return value is returned to the calling code.
This allows for a nicer implementation of `prompt_bool`, and an easily implemented `prompt_int`, or other validated prompts by other developers.
Tests for the prompt functions have been added. The tests passed on the old prompt functions, and pass on the new prompt functions without modification, so the change should be 100% backwards compatible.
Fixes #1
=> Extend prompt functionality

tests/test_render.py
On the filesystem, the file is called `mañana.txt` with
`n + ~-combining`, while the python tests were looking for `mañana.txt`
with `literal ñ`.
=> Fix unicode filename issue in the tests

tests/test_render.py, voodoo/main.py
Jinja2 defaults to stripping trailing newlines, which upsets tools like flake8 when used to validate Python files rendered from a template.
Fixes #9.
Two `.strip()` calls was removed from the tests which were masking this issue. The tests now compare the files completely, including the trailing new line.
=> Keep trailing newlines in rendered templates

.travis.yml, README.md, copier/cli.py, copier/main.py, copier/tools.py, copier/types.py, copier/user_data.py, copier/vcs.py, copier/version.py, mm.py, setup.cfg, tests/demo/pyproject.toml.tmpl, tests/pyproject.toml.ref, tests/test_copy.py, tests/test_data.py, tests/test_prompt.py, tox.ini
@jpscaletti You said you wanted to "try this idea". So here it is:
This **PR** introduced a complete type annotation of the entire `copier` module.
*MyPy and all tests run green in my local setup.*
The general Pros and Cons of type annotations apply here as well.
The code becomes bulkier even bloated at some places. Especially as we employ many functions with long signatures, those signatures will definitely turn into multi-line monstrosities. At other places, the amount of code grew due to introducing new variables or type conversions.
It enforces stringency and makes refactoring a joy. Working on another **PR**, that for #49, the significant refactoring involved killed half the tests in my first attempt. Now my second attempt is being guided by the type annotations. It makes it easier …
=> Adding type annotations

.travis.yml, CHANGELOG.md, README.md, copier/cli.py, copier/main.py, copier/tools.py, copier/types.py, copier/user_data.py, copier/vcs.py, copier/version.py, mm.py, setup.cfg, tests/demo/pyproject.toml.tmpl, tests/demo_json_old/user_data.txt.tmpl, tests/demo_json_old/voodoo.json, tests/pyproject.toml.ref, tests/test_copy.py, tests/test_data.py, tests/test_extra_paths.py, tests/test_output.py, tests/test_prompt.py, tests/test_tools.py, tests/test_vcs.py, tox.ini
With dropping `Python 3.5` support in #52 it is time to take advantage of `Python 3.6` features. 
In the same wake, some needed cleanup on the code base might be done.
This is what this **PR** is about.
Some notable changes:
- Ditching old `format` for the new `f-strings`.
- Feeding `Path` to `shutil.rmtree`.
- Dropped support for `voodoo.json`.
- Removed `print` statements from tests.
- Removed redundant commands from `cli`.
=> Cleanup and move to Python 3.6

.travis.yml, setup.cfg
Hello,
Python 3.8 is [almost there](https://pythoninsider.blogspot.com/2019/08/python-380b4-is-now-available-for.html), so it would be nice to see tests for it on CI.
These changes also:
- add more precise classifiers
Best regards!
=> Enable tests for Python 3.8 on CI

copier/config/objects.py, tests/test_config.py
This minor `PR` implements:
- enforcing mutual exclusivity of the flags `skip` and `force` at config level
- a single test for that
Closes: #78
=> Enforcing mutual exclusivity of skip and force.

.gitignore, README.md, copier/config/objects.py, tests/demo_normal_jinja2/TODO.txt.tmpl, tests/demo_normal_jinja2/copier.yml, tests/test_config.py, tests/test_normal_jinja2.py
- Alter comments syntax to match project templating syntax: `[# This is a comment now #]`.
- Document and test the way to restore Jinja2 default syntax. This is not obvious otherwise.
- Update Jinja docs location.
=> New Jinja defaults, document how to restore them

README.md, copier/config/factory.py, copier/config/user_data.py, copier/tools.py, copier/types.py, tests/demo_logfile/.copier-answers.yml.tmpl, tests/demo_logfile/copier.yml, tests/demo_logfile/round.txt.tmpl, tests/test_logfile.py
- If the copy destination exists and has a `.copierlog.yml`, all questions asked in the template `copier.yml` file will get the answer found in `.copierlog.yml` by default.
- For now, there are no `_private` variables in the copierlog, but in the future there might be, so I'm documenting that now.
- Add docs for some of Copier's hidden features.
- Add `to_nice_yaml` filter, to be able to dump beautiful YAML. [This name matches that on Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#filters-for-formatting-data) just in case somebody wants to share templates among both engines, although do not take that as an official support statement.
- Add a test that copies a folder with default data, then copies with altered data, and then copies again with default …
=> Add .copier-answers.yml to remember last answers

copier/cli.py, copier/config/factory.py, copier/config/objects.py, copier/main.py, copier/tools.py, copier/types.py, setup.cfg, tests/test_cli.py, tests/test_config.py
TODO:
---
This is a totally breaking PR. It had to come sooner or later...
Before this patch, copier had some ugly problems:
- If a file was called `--exclude`, you couldn't add it to `--extra-paths` due to using `nargs='*'` in an option. It is a weird thing that `ArgumentParser` allows to do, but can potentially lead to unfixable problems.
- Argument parsing was a little bit handycraft work.
Meet [Plumbum](https://plumbum.readthedocs.io/), the swiss army knife for CLI packages:
- CLI has been refactored as a plumbum application.
- The application now includes 2 subcommands: `copy` and `update`.
- If called without args, or with 1, it will use `update`.
- If called with 2 args, it will use `copy` (this preserves old usage unchanged, unless you are copying from a template called `copy` or …
=> Basic support for automatic copy updates

copier/cli.py, copier/config/objects.py
Without this patch, a full traceback is printed when the user hits <kbd>Ctrl</kbd> + <kbd>C</kbd>.
Now it's more elegant:
=> Handle KeyboardInterrupt elegantly

copier/config/__init__.py, copier/config/factory.py, copier/config/objects.py, copier/main.py, copier/tools.py, tests/test_config.py, tests/test_tools.py
As explained in #110, the dangling parameters for methods keep on complicating development.
A full code refactoring is too much work for now, but I did a little refactoring which consists in:
- Merge `Flags` into `ConfigData`, and remove anything related exclusively to flags.
- Any method that uses arguments from `ConfigData` gets instead a `conf: ConfigData` argument.
- `get_jinja_renderer()` removed; it's not useful as its little work can easily be done by `Renderer` itself.
This way, whenever we need a new config, we can just add it to `ConfigData` and use it more widely.
A full refactoring is still needed IMHO, where we have a main `Copier` class which handles its state and everything it needs (or it could be `CopierApp` instead), but that's more a design decision to be taken by the …
=> Reduce code complexity

README.md, copier/config/objects.py, copier/main.py, tests/demo_exclude/bad/subdir/file.txt, tests/demo_exclude/copier.yml, tests/test_exclude.py
Excluding a folder and its contents didn't exclude its subfolders.
Now, excluding a folder excludes all its files and subfolders.
=> Exclude recursively

.github/workflows/ci.yml, pyproject.toml
This **PR** implements building `copier` via `poetry`.
The build is published via a GitHub Action to Test-PyPI and then PyPI.
The build should only be triggered on tagged commits being merged into `master`.
Note: Right now I am waiting for a transfer of the copier project on Test-PyPI from the original author @jpscaletti. Until then this **PR** will not be merged.
See also:
- https://github.com/pypa/gh-action-pypi-publish
Closes: #130
=> Implement build + publish via CI

copier/tools.py
Leverage pyyaml for a couple of jobs:
- Harden the possibility of dumping unsafe YAML, which was almost impossible already, but it's safer now.
- Do not sort twice; pyyaml already sorts.
=> Safer & faster YAML dump

copier/config/user_data.py, pyproject.toml, tests/test_complex_questions.py
When using the `--data` CLI option, all incoming data are strings. This is the expected behavior because at this point we still don't know the expected types of all answers (we don't even know the questions).
Now the type casting is done smartly when strings come in any form.
There are 2 special cases handled here:
1. When the expected type is bool and the incoming data is string. Handled by YAML because strings like "false", "0" and "no" would evaluate to `True` otherwise.
2. When the expected type is JSON or YAML but the incoming data is not a string. This can only happen when data comes in from API calls (not CLI) or is loaded from default answers in `copier.yml`. In these cases, we don't need to do any type casting, because the input is already a scalar.
=> Make sure --data works

.pre-commit-config.yaml, README.md, copier/config/factory.py, copier/config/objects.py, copier/tools.py, tests/demo_answersfile/copier.yml, tests/demo_answersfile/round.txt.tmpl, tests/test_answersfile.py, tests/test_config.py
Secrets questions are available in the jinja render context, but are not logged into `.copier-answers.yml` by default.
To mark a question as secret, just set `secret: true` into its definition. You can also pass a list of question keys in `_secret_questions` if you prefer.
---
Also included:  Run linters under poetry venv
=> Add secret questions support

CHANGELOG.md
As `3.0.0` is going to be a big release I have substructured the section into user-facing changes ("features") and developer-facing ones ("other").
@Yajo Could you add the changes you have made leading up to the release of `3.0.0.`, so far?
=> Update changelog for 3.0.0

.pre-commit-config.yaml, copier/__init__.py, copier/cli.py, pyproject.toml
This is a regression from #162 where `__version__` was removed due to conflicts with how black and poetry-dynamic-versioning work.
Now those conflicts are fixed and `copier --version` works again. This was what it was returning before:
```bash
➤ copier --version
copier (version not set)
```
BEWARE: In a development, it will always return `0.0.0`, but this is expected because poetry-dynamic-versioning autopatches this on release.
In `.pre-commit-config.yaml`, `require_serial: true` is added to all local tasks that run under `poetry run`. This is because when entering `poetry run`, poetry-dynamic-versioning does its magic and patches the versions in `pyproject.toml` and `__init__.py`, and unpatches them when ending the execution. If running in parallel (default pre-commit behavior), some …
=> Allow CLI to display version with `copier --version`

copier/cli.py, tests/demo_simple/[[ _copier_conf.answers_file ]].tmpl, tests/test_cli.py
This is a switch attribute, not a flag.
Without this patch, using this feature yields this error:
```
➤ copier -fa .altered-copier-answers.yml update
Traceback (most recent call last):
File "/home/yajo/.local/bin/copier", line 8, in <module>
sys.exit(CopierApp.run())
File "/home/yajo/.local/pipx/venvs/copier/lib64/python3.7/site-packages/plumbum/cli/application.py", line 577, in run
inst, retcode = subapp.run(argv, exit=False)
File "/home/yajo/.local/pipx/venvs/copier/lib64/python3.7/site-packages/plumbum/cli/application.py", line 572, in run
retcode = inst.main(*tailargs)
File "/home/yajo/.local/pipx/venvs/copier/lib64/python3.7/site-packages/copier/cli.py", line 17, in _wrapper
return method(*args, **kwargs)
File "/home/yajo/.local/pipx/venvs/copier/lib64/python3.7/site-packages/copier/c …
```
=> Fix --answers-file

copier/main.py, tests/test_updatediff.py
There was a bug in how update diff was computed. As you can see, the temporary copy that was made to produce that diff didn't get the same answers as the current project. Thus, every time the user answered something different, a diff was generated and a `.rej` file was created.
Just try this and you'll see:
```bash
copier -f update
git add .
git commit -m updated
copier -f update
git status
```
The 2nd time you update, all files should be identical and untouched. However, that wasn't the case.
I took the chance to update this test's fixture from `dst` to `tmpdir`, which is more standard and comfortable to debug.
=> Fix updates getting diffed without proper answers

copier/main.py, copier/vcs.py, tests/conftest.py, tests/test_updatediff.py
When somebody calls `copier update` to reapply a template, respecting subproject evolution, but just to apply some changes to some answers, the updatediff system reverted those changes.
Now they are respected, so if calling `copier update` with new data, that new data will be applied to the subproject.
The basic fix is that when creating the temporary copy in the old commit (the one used to compare), it is created using last answers obtained from the subproject, excluding any new answers passed by the user.
#169 improved the situation but certainly it didn't fix it completely. This hardened test proves it works better now.
=> Fix updatediff when using copier update with --data

.github/workflows/ci.yml, .github/workflows/coverage.yml, copier/main.py, tests/helpers.py, tests/test_updatediff.py
- Do not produce contextless diff (`--unified=0`), as it leads to weird results sometimes. `.rej` files provide a saner output. Actually https://git-scm.com/docs/git-apply#Documentation/git-apply.txt---unidiff-zero recommends not using contextless patches.
- Ask `git diff` to *never* join 2 code hunks, even if they are only separated by 1 line (`--inter-hunk-context=-1`). This gives Copier most chances to reduce the amount of rejected hunks.
- When a template is to be reformatted by a pre-commit hook after copy, make sure git hooks are respected, so the updated diff matches reality more closely.
- Add and use a new helper to comfortably build a file tree from a test, to provide a way to avoid having dangling sample trees and git samples.
=> Update diff fixes

.github/workflows/ci.yml, .github/workflows/coverage.yml, .prettierrc.yml, CHANGELOG.md, CONTRIBUTING.md, README.md
Add `proseWrap: always` to prettier configuration, and re-run pre-commit
This makes YAML and MD files to be automatically wrapped when possible and when it doesn't alter the content meaning. All looks better this way.
Be more specific about what those `*.rej` files are and what to do with them.
=> Update docs and add better autoformatting for them

README.md, copier/config/factory.py, copier/config/user_data.py, copier/tools.py, copier/types.py, tests/demo_templated_prompt/copier.yml, tests/test_templated_prompt.py
=> Add prompt templating

copier/config/user_data.py
- Help messages were too separated from question and too close to previous question due to weird newlines.
- Secrets had no indication that they were secrets. Now they have a 🕵️ icon.
Before:
After:
=> [IMP] Make prompts more beautiful

pyproject.toml
Just noticed that pytest-xdist was listed in the "production" dependency, which seems wrong.
=> Move pytest-xdist as development dependency

copier/config/factory.py
It was generating deprecation warnings.
Not sure why they deprecated it since it was more convenient.
=> Stop using deprecated semver.compare function

README.md, copier/cli.py, copier/config/factory.py, copier/config/objects.py, copier/main.py, tests/demo_subdirectory/conf_project/conf_readme.md, tests/demo_subdirectory/copier.yml, tests/test_config.py, tests/test_copy.py, tests/test_subdirectory.py
Well, this required less code than I thought! I guess I could add more tests, particularly when updating a project.
TODO:
Fixes #183
=> Add subdirectory option

copier/config/factory.py, copier/config/objects.py, copier/config/user_data.py, pyproject.toml, tests/test_complex_questions.py, tests/test_config.py, tests/test_templated_prompt.py, tests/test_tools.py
- `ConfigData` objects now know where do answers come from.
- Their `.data` attribute is now a computed property that merges all those answer sources in priority order.
- To merge dicts, `ChainMap` is used extensively.
- `query_user_data` gets both `last_answer_data` and `forced_answers_data` instead of the single `answers_data` argument it got before.
- By knowing where does an answer come from, now Copier avoids asking something if the user already answered that from other source. For example, if you use `copier -d some_question=some_answer copy $src $dst`, then Copier will not ask you about `some_question` again, because you already answered that. 🎉
- All answer sources are deep-copied to avoid modifying mutable dicts and affecting further copier executions.
- A minimal amount of tests …
=> Remember answer procedence

README.md, copier/main.py, tests/test_migrations.py
When migrating a template, it can happen that the answers spec is modified.
When that happens, the migration script should modify the answers file. Thus, the update process should reload answers after running pre-migrations.
That's what it is doing now with this patch.
@Tecnativa TT23705
=> Support pre-migration scripts that alter .copier-answers.yml file

tests/conftest.py, tests/helpers.py, tests/test_answersfile.py, tests/test_cleanup.py, tests/test_cli.py, tests/test_complex_questions.py, tests/test_config.py, tests/test_copy.py, tests/test_demo_update_tasks.py, tests/test_extra_paths.py, tests/test_migrations.py, tests/test_normal_jinja2.py, tests/test_output.py, tests/test_tasks.py, tests/test_templated_prompt.py, tests/test_tools.py, tests/test_updatediff.py
This is redundant with pytest's native `tmp_path` fixture, so we use that one instead now.
=> Remove `dst` fixture

copier/config/factory.py, tests/test_copy.py, tests/test_prompt.py, tests/test_vcs.py
Before this patch, a templated default was counting as init data because it was different from the original default after rendereing, making copier believe the user provided an answer.
This patch fixes #230 by avoiding to parse questions that have no init data answer in the step of filling `data_from_init`. Those defaults will be used later as `data_from_asking_user` if needed.
---
Fix failing tests.
https://github.com/jpscaletti/siht disappeared, so these tests were failing now. Fixed by using own copier repo to test.
=>  Avoid templated defaults counting as init data

copier/main.py
It seems that the proper command was `git diff-tree` and not `git diff`, which was accidentally working until today, where some things got fixed on Git 2.28 and GH actions updated their images to use that version of Git and broke everything for us.
FTR here's a broken CI: https://github.com/copier-org/copier/runs/945692746
=> Make Copier work with Git 2.28

.github/workflows/automerge.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .pre-commit-config.yaml, README.md, copier/main.py, copier/tools.py, copier/vcs.py, poetry.lock, tests/demo_migrations/copier.yaml, tests/demo_migrations/migrations.py, tests/demo_migrations/tasks.py, tests/demo_migrations/tasks.sh, tests/test_config.py, tests/test_copy.py, tests/test_migrations.py, tests/test_output.py, tests/test_updatediff.py, tests/test_vcs.py
Let's see if tests work under windows or mac.
Continuation of #213
=> Test Windows & Mac OSX

.editorconfig, CHANGELOG.md, CONTRIBUTING.md, README.md, docs/api/index.md, docs/configuring.md, docs/creating.md, docs/generating.md, docs/updating.md
Mkdocs uses `python-markdown`, and [they say](https://python-markdown.github.io/#differences):
> The syntax rules clearly state that when a list item consists of multiple paragraphs, “each subsequent paragraph in a list item must be indented by either 4 spaces or one tab” (emphasis added). However, many implementations do not enforce this rule and allow less than 4 spaces of indentation. The implementers of Python-Markdown consider it a bug to not enforce this rule.
As we were using 2 spaces for markdown files (which looks better in source code), some indented lists were not displaying properly in the docs page.
Thus I change the setting to 4 spaces. Prettier will now enforce them, and mkdocs will display things properly.
=> Add 4-space indentation to .md files

.github/workflows/ci.yml, .github/workflows/coverage.yml, README.md
This is needed to test the master branch if it was automerged (which doesn't trigger workflows).
Also I fixed the link for that CI badge.
=> Allow to trigger CI manually

copier/cli.py, docs/configuring.md, poetry.lock, pyproject.toml
- Add `only_diff` docs.
- Link CLI docs with those from configuration.
- Add link on `copier --help` to the docs.
- Include `copier --help-all` in the online docs.
---
Inclues this commit too:
Add docs dependencies to dev dependencies 
This is a workaround for python-poetry/poetry#2555 that should be reverted after it's fixed and a new poetry is released.
=> Better docs for CLI

copier/cli.py, copier/config/factory.py, copier/config/objects.py, copier/main.py, copier/vcs.py, docs/configuring.md, poetry.lock, pyproject.toml, tests/test_migrations.py
Before this patch, Copier didn't ignore prereleases when detecting latest template tag.
This is mostly a bug because there's no way to safely upgrade a template to the latest non-prerelease tag automatically.
This a behavioral change that probably didn't hit anybody out there, but enough to make a new big release.
=> Add --prereleases support

copier/main.py, tests/test_migrations.py
Scenario:
1. Your project is in version `v1`.
2. You update ito `v2a1` using `--prerelease`.
3. Later, you just update without passing `--prerelease`.
Current result: Copier will try to downgrade your project to the latest normal release. Migrations do not work backwards, so this will leave your project broken.
Expected result: Copier forbids downgrading.
@Tecnativa TT23705
=> Forbid downgrades

.github/workflows/ci.yml
1. Run when a release is published, not created. You might create it as draft and, then, after publishing, it wouldn't get run.
2. Install from pip after restoring cache, not before. To install faster.
=> FIx publish workflow

mkdocs.yml, poetry.lock, pyproject.toml
- `pymdown-extensions` v8 support was added in `mkdocstrings` v0.13.0
- `mkdocstrings` v0.13.1 fixes cross-references links (they are now relative to each other)
Therefore we were able to clean up the Poetry dependencies a bit :slightly_smiling_face:
=> Update docs dependencies versions

.github/workflows/ci.yml, copier/config/user_data.py, docs/configuring.md, poetry.lock, pyproject.toml, tests/test_config.py
Before this patch, using `!include` was a bit absurd because it would fail under any useful scenario:
- Including with a glob.
- Trying to include more than 1 file.
Now all those are supported, and they can coexist. Besides, the patch is quite simple, which makes it more attractive.
Fix #237.
=> Allow multidoc copier.yml with glob include

copier/cli.py
There is a small typo in copier/cli.py.
Should read `subproject` rather than `subrpoject`.
=> docs: Fix simple typo, subrpoject -> subproject

copier/config/factory.py, docs/configuring.md, tests/test_config.py, tests/test_copy.py
When adding the `exclude` option from CLI/API, it extends the definitions found in `copier.yml`.
When adding it in `copier.yml`, it replaces the defaults.
Fixes #215, which explains that it was very unexpected that excluding some extra things included a lot of other things by accident.
=> Make exclude extend if called from CLI/API

copier/cli.py, copier/config/factory.py, docs/configuring.md, tests/test_updatediff.py
This flag was not working fine, after all.
Also, the only difference between `copier copy` and `copier update` is that copying should ignore subproject history, while updating should respect it.
Thus, the real CLI reflection of the `only_diff` option is whether you're using `copier copy` or `copier update`. Well, that's how it is now.
Besides all this, the real behavior of `only_diff=False` wasn't being tested. Fixed also, and updated docs.
Fixes #270.
=> Remove --only-diff flag

copier/config/factory.py, tests/test_minimum_version.py
Without this patch, any template with `_min_copier_version` would fail without need.
=> Allow running copier when installed in editable mode

docs/updating.md, mkdocs.yml, poetry.lock, pyproject.toml
Resolves #239.
I think I managed to get a nice mermaid graph:
One problem though: prettier does not understand markdown admonitions and dedents/breaks them.
Not sure if we should just drop the admonition, or find a way to make prettier happy. 
EDIT: ref: https://github.com/prettier/prettier/issues/9154
=> Document the update process

copier/config/user_data.py, poetry.lock, pyproject.toml, tests/test_prompt.py
When https://github.com/tmbo/questionary/pull/70 gets fixed, this commit should be rolled back.
For now, I have to remove this support because [otherwise I cannot publish Copier to Pypi](https://github.com/copier-org/copier/runs/1241180809?check_suite_focus=true).
=> Remove support for custom lexers temporarily

.github/workflows/ci.yml, .github/workflows/coverage.yml, .gitpod.yml, .pre-commit-config.yaml, CONTRIBUTING.md, copier/cli.py, copier/config/user_data.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_cleanup.py, tests/test_demo_update_tasks.py, tests/test_prompt.py, tests/test_templated_prompt.py
- Enhance status of #102 by trying to support python 3.9 and testing it. Not actually supported because of https://github.com/samuelcolvin/pydantic/issues/1985 and https://github.com/samuelcolvin/pydantic/issues/2009.
- Update pre-commit hooks that are possible to update (not prettier because of https://github.com/prettier/prettier/issues/9430).
- Update dev dependencies and pin their versions, to avoid possible future headaches.
- Reformat code with newer black release.
- Fix type problems.
- Update to new release of questionary.
- Revert https://github.com/copier-org/copier/pull/289 now that questionary supports custom lexers.
=> Update dependencies and tests for python 3.9

docs/configuring.md
"-f" makes more sense and matches https://github.com/copier-org/copier/blob/master/copier/cli.py#L138 ;)
=> fixed typo

copier/main.py, tests/test_updatediff.py
Before this patch, if the repo you were updating was shallow, Copier failed to update it.
Now it should update any repo, no matter its depth. We only need to fetch 1 commit from it, after all.
=> Allow updating a shallow-cloned repo

copier/config/user_data.py
~~If calling Copier through CLI, it's normal to convert all strings to expected data, but if calling through API, you should know what kind of data you're passing in, so it shouldn't try to be smarter than you.~~
This was going to fix #280, but after all that's not a real issue.
I'm just going to merge the improvements done while attempting to fix that, without changing Copier behavior.
=> Remove YAML casting for bool types

poetry.lock, pyproject.toml
This reverts commit 90b222377171c15964e7b68120a86430fe098f73, now that https://github.com/mtkennerly/poetry-dynamic-versioning/issues/35 is fixed.
=> Build with poetry-core

copier/errors.py, copier/template.py, tests/test_minimum_version.py
Targeting #348, from now on, if we cannot check the copier version or the installed version's major part is bigger than the template's minimal major part, there'll be proper warnings.
=> Warn major version difference

.github/workflows/ci.yml, .pre-commit-config.yaml, poetry.lock, pyproject.toml
This will help tools that analyze tags, such as coverage, poetry or PDM.
I'm positive and I assume no release will take more than 500 commits.
=> Increase checkout depth on CI

docs/configuring.md
As offered in [this discussion](https://github.com/copier-org/copier/discussions/376#discussioncomment-562965), I added my extension in the list of extensions suggested in the docs :slightly_smiling_face:
=> docs: Add copier-templates-extensions in the extensions list

copier/__main__.py, tests/test_cli.py
Being able to run Copier with `python -m copier` is really useful for debugging purposes.
For example in PyCharm and VSCode, you can create a new "Run" configuration by only providing a module name (not a script path or anything else, just the module name).
Without the `__main__` module, these configurations do not work:
```console
% poetry run python -m copier
/home/pawamoy/.cache/pypoetry/virtualenvs/copier-AExR1Oeb-py3.9/bin/python: No module named copier.__main__; 'copier' is a package and cannot be directly executed
```
=> feat: Add `__main__` module allowing to run `python -m copier`

copier/main.py, copier/user_data.py, tests/conftest.py, tests/helpers.py, tests/test_complex_questions.py, tests/test_prompt.py, tests/test_templated_prompt.py
This was the case when forced, but not when ran interactively. It was a regression from the v6 refactor.
Fixes https://github.com/copier-org/copier/issues/327.
=> fix: remember user answers while running interactively

copier/main.py, tests/test_updatediff.py
Fixes https://github.com/copier-org/copier/issues/369, which was a regression from the refactor.
=> fix: consider template skip_if_exists when updating

CHANGELOG.md, docs/configuring.md, tests/conftest.py, tests/test_complex_questions.py
- Inform about `null` value being converted to choice key.
- Warn about problems when using multiple types in choices.
Fixes https://github.com/copier-org/copier/issues/405.
=> int-autotruncated

copier/user_data.py, tests/conftest.py, tests/test_complex_questions.py, tests/test_prompt.py, tests/test_templated_prompt.py
I was expecting that calls in this form matched all strings in sequence. It turns out that [the docs][1] clearly state that it only tries to match one of them.
Thus, fixing the tests to avoid false positives.
[1]: https://pexpect.readthedocs.io/en/stable/api/pexpect.html?highlight=expect_exact#pexpect.spawn.expect_exact
=> fix: wrong usage of expect_exact([...])

CHANGELOG.md, copier/main.py, tests/test_copy.py
When copying a file, make sure its permissions are the same as those of the file in the template.
Fixes https://github.com/copier-org/copier/issues/361.
=> fix: inherit permissions

CHANGELOG.md, copier/main.py, tests/test_prompt.py, tests/test_updatediff.py
The copier answers file (`.copier-answers.yml` by default) should be updated always, and everybody is almost excessively warned to NOT touch that file by hand and let Copier handle it. Thus, it makes no sense to ask users whether it should be updated on conflict.
Fixes https://github.com/copier-org/copier/issues/325.
=> feat: do not ask for overwriting copier answers file

copier/user_data.py, tests/test_prompt.py
When the question is YAML or JSON and it is multiline and has a default value, that one should be prompted in multiline mode automatically.
It includes a test that will always fail (thus it is skipped). Gotta fix that some day when I'm more pro in python-prompt-toolkit stuff. For the time being, manual test is enough and this works!
I also removed some garbage found here and there.
Fixes https://github.com/copier-org/copier/issues/298.
=> fix: multiline default values prompted

copier/cli.py, docs/generating.md, docs/updating.md
Try to answer a good question: when you upgrade one subproject from template v1 to v2, the template itself needs to be properly rendered in v1 to be compared to the subproject and extract the diff... well, we all know this at this point. But if Copier 6 renders differently the template v1 as compared to how Copier 5 would, then the template developer is on big trouble: How to evolve a subproject from a Copier v5-only template to a Copier v6-only template?
Fix https://github.com/copier-org/copier/issues/348
=> docs: migration strategies across major copier versions

.gitignore, CONTRIBUTING.md
Fixes #154 
The docs tell the user to run `poetry config virtualenvs.in-project true --local`, which will create a `poetry.toml` file, which is why we ignore it in `.gitignore`. If you believe the file should be tracked instead, let me know, though I'd probably argue against.
=> docs: Tell about creating the venv in the project

copier/main.py, docs/configuring.md, tests/helpers.py, tests/test_empty_suffix.py
If a unicode decode error is raised
while trying to compile a file as a Jinja2 template,
and the templates suffix is empty,
we fallback to copying this file as is.
Fixes #433.
=> fix: Fix unicode error on binary files

poetry.lock, pyproject.toml
Bumping `iteration-utilities` allows Windows to install the dependency without having to build it first.
Fixes #439.
=> fix: Bump `iteration-utilities`

tests/demo_migrations/migrations.py, tests/test_migrations.py
In 745a4904152058b1095ce72480a3dc30c446c88a I added this new feature, but did not add a test for it.
=> test(migrations): add test for new PEP 440 environment variables in migrations

CHANGELOG.md, README.md, copier/vcs.py
When git 2.27 or newer is installed, we can add `--filter=blob:none` to avoid getting useless information from the git server. This makes clone much faster if your template has a big history.
Close https://github.com/copier-org/copier/issues/450 (it does not exactly fix it, but maybe makes it irrelevant).
=> perf(clone): clone faster without blobs

copier/vcs.py
Fixes:
```
git version
git version 2.24.3 (Apple Git-128)
Version("git version 2.24.3 (Apple Git-128)".split()[-1].replace(".windows", "+windows"))
raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'Git-128)
```
=> relax git semver parsing

CHANGELOG.md, copier/errors.py, copier/main.py, tests/helpers.py, tests/test_interrupts.py, tests/test_prompt.py
Use case: I'm using the copier api and would like to capture partially completed answers. When completing long questionnaires it's sometimes :sadpanda: to ctrl-c and repeat your work. I plan on:
- catching this exception
- writing the `e.answers.user` out to a file.
- on subsequent runs, checking for it's existence and populating `run_copy(defaults=partial_answers)`.
I suspect the above procedure could likely be generalized as a first class feature in the project e.g. copier could handle writing a `~/.copier_answers_partial.json`  or `~/.coper_{{template_name}}_answers_partial.json`, or even write out to `SubProject.last_answers`.
=> raise CopierAnswersInterrupt on partial answers

CHANGELOG.md, copier/main.py, copier/user_data.py, tests/test_config.py
This works in conjunction with https://github.com/copier-org/copier/pull/476, but is independent of it. If partial answers are written out to a file, they can be re-loaded as default overrides to whatever is specified in the template allowing one to resume progress.
Some code that uses the combination of these two MRs:
```
PARTIAL_ANSWERS = Path('~/.copier_partial.json').expanduser()
kwargs = {}
if Path(PARTIAL_ANSWERS).exists():
with open(PARTIAL_ANSWERS) as f:
kwargs['default_overrides'] = json.load(f)
try:
result = copier.run_auto(TEMPLATES_SRC, os.getcwd(), **kwargs)
except copier.CopierAnswersInterrupt as e:
with open(PARTIAL_ANSWERS, "w") as f:
f.write(json.dumps(e.answers.user))
print("Wrote partial answers to %s" % PARTIAL_ANSWERS)
```
Demo of these two features working together: …
=> allow overriden defaults in questionnaire

tests/test_cleanup.py
This was already happening, but the test is now more complete.
Fix https://github.com/copier-org/copier/issues/262 by just asserting it was fixed already.
=> test: make sure copier won't delete a preexisting folder

.github/workflows/ci.yml, CHANGELOG.md, README.md, copier/template.py, poetry.lock, pyproject.toml, tests/helpers.py, tests/test_templated_prompt.py
Also see https://iscinumpy.dev/post/bound-version-constraints/ for why I didn't cap with `<4.0` or `<3.12`.
=> build: Accept Python 3.11 as requirement

poetry.lock
pywin32 303 was just released, it should help fix CI for Python 3.11 + Windows.
=> chore: Update lock file

docs/comparisons.md, mkdocs.yml
=> docs: use footnotes and enable navigation.tracking

docs/js/refresh_on_theme_switch.js, docs/updating.md, mkdocs.yml
Fixes #541 
Not as pretty as the Material for MkDocs Insiders integration, but I guess users don't usually switch theme that often, even less so while looking at a diagram, so I think that is totally acceptable (also, glitches in the GIF just come from my way of recording, using peek).
=> docs: Change diagram colors when switching between dark and light themes

docs/configuring.md
Using the syntax stated in the current documentation, I get this error when running `copier`:
```
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got <variable>
```
Using `{%` instead of `{{`, it works as expected.
=> Update configuring.md "Conditional files" section

tests/test_templated_prompt.py
The now() template builtin is being used in the test and is an alias
for datetime.utcnow(). The now however, just uses datetime.now(). This
means that my datetime.now() will always make this test fail.
Signed-off-by: David Stanek <dstanek@dstanek.com>
=> test: fix date comparison not working in my timezone

CHANGELOG.md, copier/main.py, docs/generating.md
This PR simply adds a header message upon running copier to indicate to the user the template version being copied / updated from, eg.
```
~/copier$ python -m copier --force ~/my_template ~/new_project
Copying from template version v0.1.1
identical  .
identical  update.py
identical  src
identical  src/unix
...
```
I'm a relatively new user of copier and did not realise that its normal behavior is to always use the latest tag of a template repo, rather than the current master.
I found this particularly confusing when working from a local clone of a template under development. I'd make changes to the template, then re-run copier to check they all worked. Sometimes copier used my new changes, other times it seemed to copy really old files instead. It took me far longer than you'd think to …
=> Print header specify template version being used.

copier/main.py, docs/configuring.md, tests/test_complex_questions.py
A skipped question was not saved by Questionary, so I need to check if the answer is exactly like the question and, in that case, re-render it again.
Docs clarified to avoid false expectations on what should be the answer.
Fixes https://github.com/copier-org/copier/issues/529
=> fix: correct default for skipped questions

docs/configuring.md
This was already explained when running `copier --help`, but it still caused some confusion on users.
Fixes https://github.com/copier-org/copier/issues/579
=> docs: clarify that answers file path must be relative to project root

docs/configuring.md, mkdocs.yml
Also explain why it's a bad idea.
Fixes https://github.com/copier-org/copier/issues/578
=> docs(subdirectory): explain how to use subdirectory to host multiple templates in a single git repository

CHANGELOG.md, copier/main.py, docs/configuring.md, tests/test_tasks.py
This PR proposes adding a new built-in jinja variable `_copier_python` that provides the `sys.executable` path such that it can be used to run a script in a repeatable fashion, always using the same python envinroment that copier is installed into.
In my usage of `copier` I want to run a python script as a `task` to manage some post-template operations. I'd prefer not to use invoke or any other third party tool that requires dependencies to be manually pre-installed.
``` yaml 
_tasks:
- python update.py
```
Initially this appeared to be working fine, but then some other people re-using the template ran into a range of issues; `import yaml` failing, or `python` cannot be found etc. This issue: https://github.com/copier-org/copier/issues/324 is closely related.
I realised pretty quickly …
=> feat: Add jinja variable "_copier_python" to get sys.executable.

poetry.lock, pyproject.toml
'environmentfilter' is renamed to 'pass_environment', the old name is removed in Jinja 3.1; however, jinja2-ansible-filters doesn't provide a homepage link on Pypi, so pinning here
Fixes #622
=> pin jinja2 to version that works with jinja2-ansible-filters 1.3.0

copier/template.py, tests/test_updatediff.py
I was wrongly using `.dev`. Use `.post`, just like dunamai.
Fixes https://github.com/copier-org/copier/issues/603.
TODO:
=> fix: wrong detection of untagged commits

poetry.lock, pyproject.toml
Finally https://gitlab.com/dreamer-labs/libraries/jinja2-ansible-filters/-/merge_requests/15 was merged and released, so we can update to latest jinja.
Closes https://github.com/copier-org/copier/pull/642
=> build(deps): bump jinja2 and jinja2-ansible-filters

CHANGELOG.md, copier/main.py, tests/test_complex_questions.py
Before this patch, an answers file could remember answers to questions that were not present in the questionary.
STR:
1. In one project, apply one template that has a `.copier-answers.yml` file.
2. Now apply another template that has a different default value in `_answers_file`.
3. The second answers file would contain answers to the 1st template too.
@moduon MT-616
=> fix: stop remembering answers nobody asked

copier/main.py, copier/template.py, docs/creating.md, tests/test_copy.py
When targeting reproducible builds, we need to have exact and immutable hashes.
Until now, there was only one way to get template commit. You could only get the tag, or the best serializable approach to obtain a commit from a tag.
Using this new helper, you can get what you need.
@moduon MT-83
=> feat: support getting template commit hash with `{{ _copier_conf.vcs_ref_hash }}`

copier/template.py, copier/user_data.py, devtasks.py
There are small typos in:
- copier/template.py
- copier/user_data.py
- devtasks.py
Fixes:
- Should read `multiline` rather than `mutliline`.
- Should read `descriptive` rather than `descripted`.
- Should read `artefacts` rather than `artefacrts`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

docs/configuring.md
I've recently discovered Copier, and while browsing the documentation, I've spotted a couple of instances where masculine pronouns (he/him) are used to refer to the user. This PR changes these occurrences to use a popular gender-neutral alternative, they/them (see e.g. https://apastyle.apa.org/style-grammar-guidelines/grammar/singular-they).
This is a very small change, but I thought it would be worth opening a PR if it can help make these already excellent docs a tiny bit more inclusive for all readers. Thanks again for your work on this amazing tool!
=> docs: use gender-neutral pronouns to refer to user

docs/configuring.md
As you can see at the end of the [Advanced promt formatting](https://copier.readthedocs.io/en/stable/configuring/#advanced-prompt-formatting) section in the "Configuration" part of the docs, one of the code blocks is not correctly formated due to missing three backticks (`` ``` ``).
=> Fix missing backticks in configuring.md

poetry.lock
I've updated `poetry.lock` (with `poetry lock --no-update`, i.e. without resolving the dependencies) using [Poetry v1.1.15](https://github.com/python-poetry/poetry/releases/tag/1.1.15) which [sorts extras and extras dependencies](https://github.com/python-poetry/poetry/pull/6207), resulting in a more deterministic lock file and hopefully smaller diffs upon changes. In order to benefit from the improvement in Poetry v1.1.15, only Poetry v1.1.15+ should be used for updating dependencies from now on.
=> chore: update poetry.lock using Poetry v1.1.15

pyproject.toml
I've removed the `line-length` setting for Black because 88 characters is the default value anyway, so it's redundant to set it explicitly.
=> chore: remove Black's default line length setting

poetry.lock, pyproject.toml
Capping the Python version (e.g. `<4`) is a bad practice, so I've removed it.
* https://github.com/pypa/packaging.python.org/pull/850
* https://iscinumpy.dev/post/bound-version-constraints/#pinning-the-python-version-is-special
* https://discuss.python.org/t/requires-python-upper-limits/12663
=> build(deps): remove upper bound from Python version specifier

pyproject.toml
I've simplified the `isort` config in `pyproject.toml` by using the [profile "black"](https://pycqa.github.io/isort/docs/configuration/profiles.html#black). I've also removed redundant settings that explicitly set `isort`'s default values.
=> chore: use isort profile "black" and remove default settings

pyproject.toml
I've bumped Black's `target-version` setting from Python 3.6 to 3.7 as this is the lowest supported Python version. As a minor cosmetic change, I've replaced the single quotes by double quotes for better consistency.
=> chore: bump Black target version to Python 3.7

poetry.lock, pyproject.toml
I've converted all package names of dependencies to lowercase because I think it looks nicer and more consistent. Since the dependencies are sorted already, I infer these kinds of details also matter to you. :wink:
=> build: convert package names to lowercase

docs/configuring.md, docs/creating.md
I've updated the Jinja2 docs URL to v3.1.x which is the [current minimum version of the `jinja2` package declared in `pyproject.toml`](https://github.com/copier-org/copier/blob/1d6fb24ebef7d6118c8cdd40e1d11bb11d9386f0/pyproject.toml#L35).
=> docs: update Jinja2 docs URL to v3.1.x

.pre-commit-config.yaml, poetry.lock, pyproject.toml
pre-commit started failing with:
```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: AssertionError: BUG: expected environment for python to be healthy immediately after install, please open an issue describing your environment
more info:
virtualenv python version did not match created version:
- actual version: 3.10.6.final.0
- expected version: 3.10.4.final.0
```
Quick fix while https://github.com/copier-org/copier/pull/696 gets on track.
Sadly I had to rollback https://github.com/copier-org/copier/pull/752 due to https://github.com/PyCQA/isort/issues/1945.
=> build(isort): install with poetry

.pre-commit-config.yaml
I think local pre-commit hooks should use `language: system` because they are installed via Poetry instead of `pre-commit`. The way I read the [`pre-commit` docs on `language: python`](https://pre-commit.com/#python), the `language` tells `pre-commit` how to _install_ a hook. Since `isort` is now installed via Poetry, it's already installed and directly available to `pre-commit`.
Follow-up of #759.
=> chore(pre-commit): use language "system" for local isort hook

CONTRIBUTING.md
Just a minor correction: I've added two occurrences of missing punctuation in `CONTRIBUTING.md`.
=> docs: add missing punctuation in contributing guide

pyproject.toml, pytest.ini
I've moved `pytest`'s config from `pytest.ini` to `pyproject.toml` as that's where most configs are located these days, and it's also nicer to gather them in a single file instead of having one for each tool in my opinion.
=> chore(pytest): move config to pyproject.toml

.cz.toml, pyproject.toml
I've moved `commitizen`'s config from `.cz.toml` to `pyproject.toml` as that's [recommended for Python projects](https://commitizen-tools.github.io/commitizen/config/#pyprojecttoml-or-cztoml) and also nicer in my opinion.
=> chore(commitizen): move config to pyproject.toml

CONTRIBUTING.md
I've removed the host environment prerequisite `poethepoet` in `CONTRIBUTING.md` because it's installed as a dev dependency via Poetry, and since the Poetry shell is activated in the instructions, the tool is readily available without being installed in the host environment.
=> docs: remove prerequisite "poethepoet" in contributing guide

CONTRIBUTING.md
Just a minor correction: I've fixed the capitalization in one heading in `CONTRIBUTING.md`, so it's now consistent with all the other headings there.
=> docs: capitalize headings consistently in contributing guide

.pre-commit-config.yaml
I've renamed the `isort` pre-commit hook ID from `poetry_isort` to `isort` for better consistency with the other hook IDs. It's just a minor change, but I like consistency. :wink:
=> chore(pre-commit): rename isort hook ID

.pre-commit-config.yaml
I've added a pre-commit hook that runs [`pyupgrade`](https://github.com/asottile/pyupgrade) which automatically checks and updates Python syntax to newer versions of the language, so we can make sure we don't use unnecessarily old syntax which is often less convenient. I've configured `pyupgrade` to check for and update to Python 3.7 syntax which is Copier's minimum Python version at this point.
=> chore(pre-commit): add pyupgrade hook

copier/user_data.py, tests/test_prompt.py
I've fixed a rare but possible name collision between the var name of a question and the arguments of the method [`Question::render_value(...)`](https://github.com/copier-org/copier/blob/bc80d5fc9bca7fdb901ad85a97e877c443caaf08/copier/user_data.py#L398). `Question::render_value(...)` has a positional argument `value` and before this change, extra answers (a `dict`) were passed to `Question::render_value(...)` as keyword arguments by the [`Question::validate_answer(...)`](https://github.com/copier-org/copier/blob/bc80d5fc9bca7fdb901ad85a97e877c443caaf08/copier/user_data.py#L377) method, so in case a question var name happened to be literally `"value"`, there would be a name collision with the positional argument `value`.
I've verified this bug with a sample `copier.yml` file using …
=> fix: prevent name collision for question var name "value"

.pre-commit-config.yaml, CONTRIBUTING.md, poetry.lock, pyproject.toml
I've added `commitizen` as a dev dependency, made the pre-commit hook use the locally installed `cz` tool, and adapted the contributing guide accordingly.
Supersedes #766 (see the conclusion of the discussion in https://github.com/copier-org/copier/pull/766#discussion_r961298028).
=> build(deps-dev): add "commitizen" dev dependency

docs/faq.md
The `choices` items in the example on the FAQ docs page should be lowercase in order to work with the matching in the context hook example code below. Before this change, the example is inconsistent.
=> docs(faq): convert "choices" items to lowercase

docs/generating.md
Just a minor docs fix: I've added language information to code fences that were missing it.
=> docs: add missing language to code fences

CONTRIBUTING.md, docs/configuring.md, docs/updating.md
I've updated the ordered list markers to `1.`. I think it's common and good practice to always use `1.` as the marker in ordered lists instead of explicitly incrementing the marker because it simplifies changes to an ordered list.
=> docs: always use ordered list marker "1."

CONTRIBUTING.md, README.md, docs/configuring.md, docs/creating.md, docs/generating.md, docs/updating.md
Just a minor (probably a bit subjective and picky :laughing:) change: There was a mix of language identifiers for shell code blocks (`bash` and `sh`). To my understanding, `bash` refers to the [Bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) shell and `sh` (unless it's just meant as a short form of "shell") refers to the [Bourne shell](https://en.wikipedia.org/wiki/Bourne_shell). I believe none of the shell code blocks show code specific to one of the shell variants, so I suggest to use `shell` as the generic language identifier for a [Unix shell](https://en.wikipedia.org/wiki/Unix_shell).
There is no difference in syntax highlighting because all three language identifiers map to [`pygments.lexers.shell.BashLexer`](https://pygments.org/docs/lexers/#pygments.lexers.shell.BashLexer), …
=> docs: unify shell code blocks

copier/vcs.py, tests/test_vcs.py
Closes #791.
I won't be able to add a test right now, but can do later this week.
=> fix: Resolve path before checking Git bundle

docs/configuring.md
I've fixed an indentation error in the migrations config example in the docs.
=> docs: fix migrations config indentation

pyproject.toml
Just a minor change: I've sorted the dev-dependencies in `pyproject.toml`. :slightly_smiling_face:
=> build: sort dev-dependencies

README.md
I've fixed two minor grammar mistakes in the README file.
=> docs(readme): fix grammar

pyproject.toml
I've updated the `build-backend` config in `pyproject.toml` according to the [`poetry-dynamic-versioning` installation instructions](https://github.com/mtkennerly/poetry-dynamic-versioning#installation).
=> build: use poetry-dynamic-versioning wrapper for build backend

copier/main.py, copier/user_data.py, copier/vcs.py
Just a minor refactoring that reduces module imports (e.g. `import pathspec`) by preferring imports of specific names from modules (e.g. `from pathspec import PathSpec`).
=> refactor: reduce module imports

CONTRIBUTING.md
I've documented in the contributing guide that Poetry v1.2+ is required now.
Poetry v1.1 has some interoperability issues with lock files generated by Poetry v1.2 (https://github.com/python-poetry/poetry/issues/6593). Since [@dependabot uses Poetry v1.2](
https://github.com/dependabot/dependabot-core/blob/04741be8510dd4258a3892312b82136eedf8c1ce/python/helpers/requirements.txt#L7) now, I'm afraid we need to follow to avoid issues. Note that it may be necessary to purge the PyPI cache after updating to Poetry v1.2:
```shell
poetry cache clear --all PyPI
```
=> docs: require Poetry v1.2+

copier/main.py, copier/template.py, copier/types.py, tests/test_config.py
I've introduced a Data Class `Task` to model a task to execute (used internally for [tasks](https://copier.readthedocs.io/en/v6.2.0/configuring/#tasks) and [migrations](https://copier.readthedocs.io/en/v6.2.0/configuring/#migrations)).
Before, a task was represented by a dict which is less descriptive and less type-safe. Also, there was some inconsistency between tasks and migrations in terms of where additional environment variables are specified that shall be set while executing a task command. Specifically, migrations had their additional environment variables set in the `Template.migration_tasks` property while tasks had their additional environment variables set in the `Worker.run_copy(...)` method.
The slightly less pretty way of [setting the `use_shell` flag in each branch of the …
=> refactor: model a task to execute using a dataclass

docs/configuring.md
I've unified the indentation of YAML code blocks in the docs to 4 spaces per indentation level.
I think most projects use 4 spaces for Python code and 2 spaces for most other languages like YAML. However, Prettier currently cannot be configured accordingly because it doesn't support [config overrides by langauge](https://github.com/prettier/prettier/issues/5378) but only by file (pattern). Markdown indentation was changed to 4 spaces in #249 for good reasons, but as a result also e.g. YAML code blocks are formatted with 4 spaces indentation. I believe the reason why the two occurrences of 2 spaces indentation, that I'm changing to 4 spaces in this PR, weren't caught by Prettier is a result of the non-standard Markdown syntax used for …
=> docs: unify YAML code block indentation

copier/template.py
I've fixed a typing error related to the possible stage names of migration tasks. In `template.py`, the method `Template.migration_tasks(...)` declared the `stage` argument to accept three string literals: `Literal["task", "before", "after"]`. The string literal `"task"` is not a valid task stage though. Hence, I've removed it.
=> fix(typing): remove invalid migration task stage "task"

.github/workflows/ci.yml, .readthedocs.yml, CONTRIBUTING.md, devtasks.py, poetry.lock, pyproject.toml
I've organized dependencies using the new [dependency groups](https://python-poetry.org/docs/managing-dependencies#dependency-groups) feature [released with Poetry v1.2](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups). Since [Poetry v1.2 is required now](#816) anyway, I think it's nice to leverage this feature.
Thanks to dependency groups, dependencies can be defined in a more granular fashion and groups can be optional, so that it isn't necessary to always install all of them. Here's what you can do:
```shell
poetry install
poetry install --with docs
poetry install --only docs
poetry install --only main
```
Also, docs dependencies aren't exposed as a runtime extra anymore, which was just a workaround for the missing optional dev dependencies feature.
WDYT?
=> chore: organize deps with Poetry v1.2 groups

copier/user_data.py
I've removed unreachable code in an `if` condition that handles a [question choice format that isn't supported](https://github.com/copier-org/copier/blob/e8d6239f8711054cbe30ec0472f147e04479a199/tests/test_complex_questions.py#L61-L89).
The handled format is:
```yaml
choices:
- name: ...  # <--
value: ... # <--
- ...
choices:
key:
name: ...  # <--
value: ... # <--
...
```
=> refactor: remove unreachable code

README.md
I've beautified a few badges by adding brand logos. For Python and PyPI, I've adopted the logo color from the CI badge because the original logo color (a shade of blue) doesn't go well with the dark gray background color of the badges.
=> docs: beautify badges

docs/configuring.md
I've added documentation for the `_secret_questions` setting.
Closes #809.
=> docs: add `_secret_questions` setting

copier/cli.py, copier/types.py
I've removed a couple of types that were defined in `types.py` but not used anywhere.
=> refactor(typing): remove unused types

docs/configuring.md
Follow-up of https://github.com/copier-org/copier/pull/820#discussion_r979841162.
=> docs: replace default argument value N/A by `[]` for lists

copier/template.py
Just a minor cosmetic change, it's also more consistent with other similar occurrences.
Follow-up of #812.
=> refactor: use `dict` constructor as default factory

copier/template.py, tests/test_normal_jinja2.py
Since [Copier v7](https://github.com/copier-org/copier/releases/tag/v7.0.0) was released yesterday :tada:, I've removed some occurrences of deprecated code that were scheduled for removal in v7 according to the inline code comments. Trying to reduce technical debt here. :wink:
=> refactor: remove deprecated code scheduled for removal in Copier v7

copier/template.py, docs/configuring.md, tests/demo_merge_options_from_answerfiles/copier.yml, tests/demo_merge_options_from_answerfiles/include1.yml, tests/demo_merge_options_from_answerfiles/include2.yml, tests/test_config.py
Hi there 👋 
This is my first PR here and it adds code, tests and docs for merging copier settings from multiple yaml documents included into `copier.yml`.
Given the following project layout
```
|-- copier.yml
|-- foo.txt
|-- component
|-- component.yml
|-- bar.txt
```
and the files 
```yaml
...
_skip_if_exists:
- foo.txt
---
!include ./component/component.yml
```
```yaml
...
_skip_if_exists:
- component/bar.txt
...
```
the resulting value for `_skip_if_exists` will be the concatenated values from both documents i.e. `["foo.txt", "/component/bar.txt"]` instead the latest document overwriting the previous value i.e. `["/component/bar.txt"]`. 
This PR only adds logic for merging settings that are not order dependent i.e. `skip_if_exists`, `jinja_extensions`, `secret_questions` and `exclude`. …
=> Merge answerfile options

docs/configuring.md
I've cleaned up the docs a bit in the section on including other YAML files:
* Some typo and spelling fixes
* Use a code block title instead of inline YAML comment about the file path
* Minor cosmetic/consistency improvements
Follow-up of #846 (specifically, 5d1e9c6c0a07ce86ccbe1e55d13e59f56199c947 respectively 12bd54239cff91140040b8ef592d66aabdc17386).
=> docs: improve section on including other YAML files

.github/workflows/ci.yml
Let's see if this fixes the constant failures from Codecov uploads.
Inspiration: https://github.com/codecov/codecov-action/issues/557#issuecomment-1224970469
=> ci: use codecov token for uploads

docs/configuring.md
I've fixed an invalid anchor link in the docs.
=> docs: fix invalid anchor link

.github/workflows/ci.yml, copier/cli.py, copier/main.py, docs/configuring.md, docs/updating.md, tests/test_subdirectory.py, tests/test_updatediff.py
Fixes #613 
Based on #627, but:
- Supports both old (`.rej` files) and new (inline markers) conflict behavior
- Organizes the code to reduce likelihood of merge conflicts (while this PR is in development/review)
=> Flexible conflict resolution

.pre-commit-config.yaml
I've added a pre-commit hook that verifies that `poetry.lock` is consistent with `pyproject.toml` using the command:
```sh
poetry lock --check
```
=> chore(pre-commit): add poetry lock file check hook

copier/template.py, poetry.lock, pyproject.toml
Closes #889 
Installing copier on Windows with python 3.10 and no c++ compiler fails. This is due to the dependent package [iteration_utilities](https://github.com/MSeifert04/iteration_utilities) having no python 3.10 wheel file available on pypi.
Solution is to remove the dependency on the `iteration_utilities` package and find an alternative for the single line in copier where it is used. @yajo pointed out that the [funcy](https://github.com/Suor/funcy) package has a `flatten` function which would give the same result.
This PR removed the dependency on the 'iteration_utilities' package and replaces it with the [funcy](https://github.com/Suor/funcy) package.
See #890 for an alternate solution which removes the dependency and re-implements the `deepflatten` function directly in copier.
=> fix: replace dependency on iteration_utilities

README.md, docs/configuring.md, docs/creating.md
Fix #894
Signed-off-by: Xuan Hu <i@huxuan.org>
=> docs: No redundant empty lines for `_copier_answers`.

poetry.lock, pyproject.toml
I've fixed `funcy`'s version specifier to use only a lower bound. Although it's not explicitly mentioned, it looks to me like `funcy` uses SemVer, so only a lower bound should be used.
While at it, I've also placed the `funcy` dependency in alphabetic order with the other dependencies.
=> build(deps): fix `funcy` version specifier

docs/configuring.md
I've updated the docs related to backwards compatibility of the Jinja syntax defaults in older Copier versions which was dropped in Copier 7.
=> docs: update note on Jinja defaults for Copier 7+

copier/cli.py, copier/main.py, tests/test_subdirectory.py
Instead of 2 completely different implementations, just reuse the good old rej one.
However, now, after updating, search for `.rej` files and 3-way-merge those (and only those).
This will save a lot of loops, time, memory and disk I/O. Also it's shorter. Good!
Fixes https://github.com/copier-org/copier/issues/883.
=> refactor(inline): smarter inline conflict markers algorithm

.github/workflows/ci.yml
This should avoid too many :x: PRs.
=> ci(codecov): continue on error when uploading

docs/updating.md
I've improved the docs on updating a project by fixing typos, punctuation, grammar, etc.
=> docs(updating): fix typos/punctuation/grammar

copier/main.py, docs/configuring.md, docs/creating.md, tests/test_copy.py
When rendering files, the filename template may hold forward slash characters, in which case Copier attempts to write a directory structure. But it doesn't ensure the directory structure exists before writing the file.
This patch fixes it.
Related to #692
=> Make sure the parent directory of the target file exists

copier/errors.py, copier/vcs.py, docs/faq.md, tests/test_vcs.py
When using `git >= 2.27`, the filter `--filter=blob:none` is used to make the cloning process faster. Nevertheless, this can cause troubles when cloning local repositories.
=> fix: do not set git filter for local shallow clones

copier/template.py, docs/configuring.md, tests/test_exclude.py
I've changed the behavior of the default values of the [`exclude`](https://copier.readthedocs.io/en/latest/configuring/#exclude) list such that the default values are not applied when a subdirectory is specified in `copier.yml`. See https://github.com/copier-org/copier/issues/934#issuecomment-1407444680 for the original discussion.
Note that the default values remain active when the subdirectory is explicitly set to `""` or `"."` because I think this is identical to omitting the `subdirectory` setting and seems like a sensible behavior to me. WDYT, @yajo?
Also, I think it's actually a breaking change because the implicit behavior is changed and Copier template developers might need to add an explicit `exclude` list if they rely on the default values while using a subdirectory. Should this …
=> feat: ignore default excludes when using subdirectory

copier/main.py
This check is no longer needed after 7e0def672998 (fix: don't attempt to render a file if its name is empty) has been added. That commit also made this line no longer be covered by the tests.
This check made copier skip copying a file with an empty name (The path would then point to the directory containing the file).
=> fix: Remove useless is_dir check

copier/user_data.py
Just a minor typing change, but I think it's better to use `Mapping[str, Any]` instead of `t_ChainMap[str, Any]` as the return type of `AnswersMap.combined` because
1. the fact that a `ChainMap` is used to combine the answers data is an implementation detail, and
2. the combined answers data is only meant to be read and not updated which is enforced by the `Mapping` type at the type level.
As an esthetic side-effect, the import alias `ChainMap as t_ChainMap` is gone, too. :wink:
=> refactor(typing): use `Mapping` instead of `ChainMap` type

copier/main.py, copier/user_data.py
I've removed some useless code related to not asking a question, i.e. not prompting, when (a) defaults are supposed be used (e.g. `--defaults` flag) or (b) the answer is provided via CLI (i.e. `--data` flag) or API (i.e. `data` argument passed to `run_auto(...)`/`copy(...)`). The removed code was about handling this case by setting `when` to `False`, but [it seems one must be careful with using `when` for purposes other than the intended one](https://github.com/copier-org/copier/discussions/678#discussioncomment-2822746), and [using defaults](https://github.com/copier-org/copier/blob/2201d0210a57cc4d88c1d5d2369b70ea4894e2a9/copier/main.py#L394-L395) and [using answers via CLI/API](https://github.com/copier-org/copier/blob/2201d0210a57cc4d88c1d5d2369b70ea4894e2a9/copier/main.py#L378-L380) …
=> refactor: remove useless code related to not asking a question

copier/user_data.py
I've simplified casting boolean question settings to `bool` by using `cast_str_to_bool` directly instead of using `cast_answer_type(<value>, cast_str_to_bool)`, which (a) was semantically off because those values aren't answers to questions and (b) was unnecessary because `cast_answer_type(...)` contains additional logic for handling edge cases of answers that aren't relevant to those boolean-like settings values.
=> refactor: simplify casting boolean question settings

copier/main.py, copier/user_data.py, tests/test_copy.py
I've added support for validating answers provided via CLI (`--data` flag) and API (via `data` argument to `run_auto(...)`/`copy(...)`).
Closes #814.
=> feat: validate answers given via CLI/API

copier/cli.py, tests/test_cli.py
Command line option "--skip" currently does not work and is just ignored, because its value is not passed to Worker class.
=> fix: --skip option is ignored

devtasks.py, pyproject.toml
`poe lint` now uses nix if available. Otherwise, it will try to use docker or podman, by downloading the nix image and running pre-commit nix-based from there.
Fixes https://github.com/copier-org/copier/issues/931.
=> build: easier containerized pre-commit execution for friends without nix

.github/workflows/ci.yml, pyproject.toml
Hey! 
Whilst browsing through the files I found this little piece missing. 
It's just a for a documentation and consistency purposes, it seems that PyPi is anyway using the Python version constraints for determining supported Py versions.
Cheers,
Damian
=> Add 3.11 to classifiers in pyproject.toml, switch to stable 3.11 in CI

copier/cli.py, docs/configuring.md, tests/test_cli.py
I've moved the `--conflict` flag to the `copier update` subcommand as mentioned in #865.
Fixes #865.
=> fix(cli): use `--conflict` flag only in `copier update` subcommand

README.md, docs/configuring.md, docs/creating.md, mkdocs.yml, poetry.lock, pyproject.toml
I've added the [`markdown-exec`](https://github.com/pawamoy/markdown-exec) MkDocs plugin and replaced the manually written filesystem trees using Unicode characters by [`markdown-exec`'s `tree` fence](https://pawamoy.github.io/markdown-exec/usage/tree/) that automates the rendering of filesystem trees.
See https://github.com/copier-org/copier/pull/988#issuecomment-1436892212 for a prior discussion.
=> docs: use tree fence for filesystem trees

copier/template.py
I've fixed a potential race condition bug when using YAML includes in `copier.yml` when projects are generated in parallel in a single process, caused by registering a YAML `!include` constructor globally in the `yaml.FullLoader` class.
I'm not 100% sure whether this could actually cause a problem with CPython because multi-threading only parallelizes I/O-bound tasks, but I think my suggested improvement is safer in any case.
See the different behavior:
```python
from pprint import pprint
from yaml import FullLoader
from yamlinclude import YamlIncludeConstructor
class _Loader(FullLoader):
...
pprint(FullLoader.yaml_constructors)
pprint(_Loader.yaml_constructors)
YamlIncludeConstructor.add_to_loader_class(
loader_class=_Loader, base_dir="/some/base/dir"
) …
```
=> fix: don't set YAML `!include` constructor globally

tests/test_updatediff.py
I've removed an unknown `pytest` marker `pytest.mark.timeout(...)`. A warning is shown when running the test suite:
```shell-session
$ pytest tests/test_updatediff.py
...
copier/tests/test_updatediff.py:502: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
@pytest.mark.timeout(20)
...
```
The test was added in #424, but I don't think the timeout marker ever worked because [`pytest` v6.2.2](https://github.com/copier-org/copier/blob/7bbd0406b854664954dd98634a281cfff311cb7d/poetry.lock#L793-L794) was used at the time and [didn't seem to contain this marker](https://docs.pytest.org/en/6.2.x/search.html?q=timeout). …
=> refactor(tests): remove unknown timeout marker

flake.nix
Until https://github.com/NixOS/nix/issues/6771 is fixed, it's better to declare devenv's cache, so we have to host less binaries ourselves.
=> build(flake): more default cache sources

flake.nix
Oops, I did it wrong in 62b5dc36b3818ef550d21932ee49dccae5f3f494. Fixing.
=> build(flake): fix wrong spelling of substituters, and use nicer list syntax

.envrc
Before this patch, opening Copier on Gitpod made direnv freeze.
=> build(direnv): simpler config by inheriting flake configs

tests/conftest.py, tests/helpers.py, tests/test_answersfile.py, tests/test_cleanup.py, tests/test_cli.py, tests/test_complex_questions.py, tests/test_conditional_file_name.py, tests/test_config.py, tests/test_copy.py, tests/test_demo_update_tasks.py, tests/test_dirty_local.py, tests/test_empty_suffix.py, tests/test_exclude.py, tests/test_interrupts.py, tests/test_jinja2_extensions.py, tests/test_migrations.py, tests/test_minimum_version.py, tests/test_normal_jinja2.py, tests/test_output.py, tests/test_prompt.py, tests/test_subdirectory.py, tests/test_tasks.py, tests/test_templated_prompt.py, tests/test_tools.py, tests/test_updatediff.py, tests/test_vcs.py
I've added type hints to the tests, so they are type-checked by `mypy` as well, and cleaned up the tests a bit, e.g. more consistent setup of temporary template and subproject directories, formatting of template tree creation code for improved readability (IMO), consistent usage of the `pathlib` API instead of the `os`/`os.path` API, etc.
I know it's a quite big PR and probably not much fun to review :see_no_evil: - sorry about that :confused: -, but I felt the tests could use some love :smile_cat:.
=> refactor(tests): add type hints and clean up

copier/main.py, tests/test_answersfile_templating.py
Adds the ability for `_answers_file` to contain template variables. For example:
```yaml
_answers_file: ".copier-answers.{{ foo }}.yml"
foo:
type: str
```
Closes #866
Since #882 seems to have been abandoned and the tests weren't actually working, I've opened up this PR instead.
=> feat: Parse templates in _answers_file setting

copier/main.py, tests/test_migrations.py, tests/test_tasks.py
Copier now skips tasks execution in pretend mode as discussed in #950. I've extended the fix to also skip _migration_ tasks in pretend mode although they weren't explicitly mentioned in #950, but I think that is consistent behavior.
Fixes #950.
=> fix: skip tasks in pretend mode

copier/main.py, tests/test_updatediff.py
These answers could come from new user decisions or new template questions.
Before this patch, these answers were not being respected. The problem was even more evident with iline conflicts.
Or maybe it was there before and I didn't notice because `--conflict=inline` makes it more obvious.
@moduon MT-2675
=> fix: properly support diffs over updates with new answers

tests/test_vcs.py
I've added a test that ensures the latest version tag is selected with heterogeneous version formats such as `v1`, `v1.0`, `v1.0.0`, and `v1.0.1` in this as well as reverse creation order (just to be on the safe side that there's no order sensitivity of some kind).
I cannot reproduce the issue reported in #987 both on `master`, `v7.0.1`, and `v6.2.0`. Nevertheless, I think it's good to have a test that ensures the expected behavior.
Closes #987.
=> test: select latest version tag

copier/main.py, tests/test_updatediff.py
I've fixed a bug related to updating a project located in a subdirectory of a Git repo (e.g. in a monorepo). Before, Copier didn't detect merge conflicts (i.e. no `.rej` files or inline markers were created) and simply overwrote modified files in the subproject.
The fix is relatively simple. The update algorithm now recreates the subdirectory layout (or rather the relevant slice) of the original Git repo, so the diffing and applying of patches occurs consistently from the Git repo root.
Fixes #671.
=> fix: properly support update in repo subdirectory

tests/test_cli.py, tests/test_complex_questions.py, tests/test_conditional_file_name.py, tests/test_copy.py, tests/test_updatediff.py
I didn't notice a couple of missing return type hints when preparing #1057.
=> test: add return type hints

copier/template.py, tests/test_cleanup.py
I've fixed a bug where a local template in a parent folder (with a relative path component `..` in the source path) was incorrectly cleaned up.
The problem was that the path comparison
https://github.com/copier-org/copier/blob/91966047d9741099b4925612c5c0c3a0dbe2490c/copier/template.py#L226
failed when the template path contained `..` because [`Path(...).absolute()` does not perform path normalization](https://docs.python.org/3/library/pathlib.html#pathlib.Path.absolute) such as relative path resolution, so the absolute path of `clone_path` still contained `..` whereas the absolute path of `original_path` did not. I've replaced `Path(...).absolute()` by [`Path(...).resolve()` which does perform path normalization](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve).
Fixes …
=> fix(cleanup): don't clean up local template in parent folder

docs/generating.md, mkdocs.yml
I've added documentation on the supported Git URL patterns, mainly URL prefix/postfix compatibility tables in which case Copier will recognize a URL as a Git URL. This documentation is based on the `copier.vcs.get_repo(url)` function:
https://github.com/copier-org/copier/blob/47f3d59c27094e6f8ef0bc71acc74d88cbf6bb78/copier/vcs.py#L67-L95
Resolves #1043.
Would this additional documentation have helped you, @sandeeps311?
=> docs: add supported Git URL patterns

copier/main.py, copier/template.py, copier/tools.py, docs/configuring.md, tests/demo/symlink.txt, tests/helpers.py, tests/test_copy.py, tests/test_dirty_local.py, tests/test_symlinks.py
Closes #937.
This PR makes copier preserve symlinks when copying a template instead of copying the file the symlink points to.
The old behavior can be restored by setting `_preserve_symlinks` to false in `copier.yml`.
If the name of a symlink is templated it will be rendered. The targets of symlinks will only be rendered if the symlink name ends with the template suffix (`.jinja` by default).
=> feat: Preserve symlinks when copying templates

copier/main.py, copier/types.py, copier/user_data.py, docs/configuring.md, tests/test_answersfile.py, tests/test_copy.py, tests/test_prompt.py, tests/test_templated_prompt.py
I've fixed the behavior for questions without a default value when no answer is provided in the interactive questionnaire.
The new behavior is:
- `type: str` question: `""`
- `type: yaml` question: `None` (result of `yaml.safe_load("")`)
- `type: int`/`type: float`/`type: json` question: Validation error `Invalid input`
- `type: bool` question: `False` (implicit default)
- `choice: ...` question: The first choice (implicit default).
I think this new behavior is more intuitive and expected than the current one.
Fixes #355 #956.
Note: This PR does not change the behavior when the `--default` flag is passed because it is not yet clear how to deal with questions that lead to a validation error when no default value exists.
=> fix: require answer for questions without default value

copier/vcs.py, docs/faq.md, docs/generating.md, tests/test_dirty_local.py
This was the intended and documented behavior, but at some point it got broken.
Well, now it's tested and it works.
=> fix: include dirty local changes when copying HEAD

devtasks.py
Folks that have both tend to prefer podman.
=> build(lint): use podman before docker

copier/cli.py, copier/main.py, docs/configuring.md, tests/test_updatediff.py
Until today, the updatediff algorithm always used just 1 line of context when detecting conflicts. This was because:
- Solving conflicts wasn't very ergonomic with those `.rej` files around.
- More lines meant too many conflicts usually.
However, it made the diff detection less accurate.
With this change, we allow the users to configure that algorithm. Since they have now the `--context inline` option, more conflicts isn't so much of a problem.
@moduon MT-2638
=> feat: customizable update accuracy

copier/user_data.py, tests/test_copy.py
I've fixed a bug related to answer validation of questions with complex choices. Previously, choice values were collected in a set which requires the choice values to be hashable. But complex choice values such as `dict` or `list` values aren't hashable. Now, they are collected in a list.
Fixes #1108.
=> fix: fix answer validation for question with complex choices

copier/vcs.py, tests/test_copy.py
I've fixed a regression introduced by #1047 related to using a branch name as a VCS ref via the CLI switch `-r` or the API argument `vcs_ref` which caused the following error:
```
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | git reset --hard my-branch
Stderr:       | fatal: ambiguous argument '<branch_name>': unknown revision or path not in the working tree.
```
Fixes #1093.
=> fix: fix using a branch name as VCS ref

copier/cli.py
Just a minor fix of the type hint on the class attribute of the `--skip` switch.
=> style(typing): remove useless type hints

copier/user_data.py
I've removed the unused `local` field in the `AnswersMap` dataclass.
=> refactor: remove unused local overrides to answers

copier/user_data.py, tests/test_copy.py
I've fixed a bug when parsing complex-valued choices caused by an [upstream bug in Pydantic v1](https://github.com/pydantic/pydantic/issues/5523).
The workaround is to change the order of the type union so that list-style choices are parsed using the `Sequence[Any]` type because it matches before `Dict[Any, Any]` (which shouldn't match in that case at all but does due to the bug).
Related to #1108 & #1110.
=> fix: work around Pydantic bug when parsing choices

docs/creating.md
This is a really minor change, but it looks like the 'Minimal Example' filesystem graphic on the [Creating a template](https://copier.readthedocs.io/en/stable/creating/#minimal-example) page is slightly off.
According to the graphic a bit further down on the page, `.copier-answers.yml` should be found under `generated_project`, and so `{{_copier_conf.answers_file}}.jinja` should be directly inside the `my_copier_template` (not `{{project_name}}`.
=> Fix filesystem view to match later graphic (and homepage)

README.md, copier/main.py, docs/generating.md
Fantastic changes in #1143! :bow: :star_struck: :rocket:
I just updated the docs to fix a few leftovers from the past regarding usage of `copier.run_auto()`.
=> docs: replace `run_auto()` by `run_copy()`

docs/configuring.md
I've added a reference to the new `jinja2-jsonschema` extension in the docs.
Supersedes #1101.
=> docs: add reference to `jinja2-jsonschema` extension

copier/cli.py, copier/main.py, docs/configuring.md, docs/updating.md, tests/test_conditional_file_name.py, tests/test_updatediff.py
Updates not only overwrite files when actually updating, but also when applying the git diff.
Since only git-tracked subprojects can be updated, in reality there's no problem when overwriting. I find myself always overwriting and later fixing stuff with git tools.
BREAKING CHANGE: Updates will overwrite existing files always. If you need to select only some files, just use `git mergetool` or `git difftool` after updating.
BREAKING CHANGE: Flag `--overwrite/-w` disappeared from `copier update`. It is now implicit.
BREAKING CHANGE: To update via API, `overwrite=True` is now required.
Fix https://github.com/copier-org/copier/issues/741.
=> refactor: overwrite always on updates

docs/faq.md
Fix the broken link of the jinja-extension in FAQ.
=> docs: fix jinja-extension link in faq

copier/cli.py, copier/errors.py, copier/main.py, docs/configuring.md, tests/test_answersfile_templating.py, tests/test_cleanup.py, tests/test_copy.py, tests/test_demo_update_tasks.py, tests/test_jinja2_extensions.py, tests/test_migrations.py, tests/test_tasks.py, tests/test_unsafe.py, tests/test_updatediff.py, tests/test_vcs.py
I've disabled the use of unsafe features (Jinja extensions, migrations, and tasks) by default and added a new CLI switch `--UNSAFE` which enables them. Templates that don't use unsafe features are unaffected by this change. But Copier will raise an error for templates that do use unsafe features unless the `--UNSAFE` flag is passed.
I've not added an interactive prompt that asks for consent for using unsafe features because I think it's not clear how to distinguish between interactive prompting and raising an error when `--UNSAFE` is not passed. For this, I think Copier would need a switch that clearly states whether interactive or non-interactive mode is desired. Currently, `--defaults` implies this for questions.
We could add an interactive prompt in a follow-up PR ones the path forward …
=> feat: disable unsafe features by default and add `--UNSAFE` switch

README.md, docs/configuring.md, docs/faq.md, docs/generating.md, docs/updating.md
I've updated the CLI usage examples in the docs to conform with the breaking changes in v8.0.0 introduced by #1143 regarding required subcommands and subcommand flags.
Resolves https://github.com/copier-org/copier/discussions/1174#discussioncomment-6182689.
=> docs: update CLI usage examples to conform with v8

copier/main.py
I've made the type hint for the `conflict` attribute more precise by using `Literal["rej", "inline"]` instead of `str`.
@yajo Is `refactor(typing)` the correct change type in your opinion? It seemed the most appropriate to me, but I couldn't find a guideline for committing only typing changes.
=> refactor(typing): use `Literal` type hint for `conflict` attribute

copier/main.py
I've updated the docstring in the `Worker` class to state the new default conflict mode `inline` since v8.0.0. I've also removed a line comment about `inline` being still experimental.
Follow-up of #1143.
=> docs: update default conflict mode

copier/cli.py, docs/configuring.md, tests/test_unsafe.py
See rationale in https://github.com/copier-org/copier/issues/1137#issuecomment-1579304713.
=> feat: add `--trust` as a less scary alternative to `--UNSAFE`

docs/generating.md, docs/updating.md
Docs were a bit repetitive and unclear.
Targets https://github.com/copier-org/copier/issues/1170. It could even fix it?
=> docs: clarify how to use recopy to recover from broken updates

copier/main.py, copier/template.py, copier/user_data.py, docs/configuring.md, tests/test_complex_questions.py, tests/test_prompt.py
I've added support for a long awaited feature: computed values via skipped questions (`when: false`). :tada: See https://github.com/copier-org/copier/pull/1206#issuecomment-1605892551 for more details.
Supersedes #1206. Resolves #1204 #1205. Resolves (I guess ...) #1203. :stuck_out_tongue_winking_eye:
=> feat: add support for computed values via skipped questions

copier/main.py
Just a minor refactoring which simplifies setting an immutable default value for a dataclass attribute without calling the `field()` function.
=> refactor: assign immutable default value without dataclass `field()` function

copier/template.py, tests/test_config.py
I've cleaned up the internal bookkeeping logic for secret questions. The new structure will simplify raising an error when a secret question has no default value, which we discussed in https://github.com/copier-org/copier/issues/1177#issuecomment-1585556997.
There are two ways to declare a question as secret:
1. By setting `secret: true` in the config of a question.
2. By adding the variable name of a question to the `_secret_questions` list. This option is needed when a question that uses the `<name>: <default value>` syntax shall be secret.
Internally, [Copier uses the a secret questions list to omit answers to secret questions from the answers file](https://github.com/copier-org/copier/blob/1b351bc8560d19d70e927cdb2fafb4f7ce41092d/copier/main.py#L258). This list contains the variable …
=> refactor: clean up secret questions management

copier/user_data.py, tests/test_copy.py
I've fixed a bug related to validating an answer against conditional choices where multiple choices have the same value. Before, an error was raised immediately when the first choice that matched the provided answer was disabled even though another choice with the same value was enabled. Now, all choices are checked and an error is raised only when none of the matching choices are enabled.
Fixes #1233.
=> fix: fix answer validation against conditional choices with duplicate values

tests/test_subdirectory.py
Just some minor style improvement related to typing a union of literals.
=> style: use `Literal` with multiple args instead of union of `Literal`

tests/test_symlinks.py, tests/test_vcs.py
Just some minor consistency improvement regarding imports. I think it's preferable to import things like exceptions and utilities from their corresponding modules and not from the root module, and only import `run_copy`/`run_recopy`/`run_update` (and perhaps `Worker`, although I think that should be hidden long-term) from the root module.
This is a minor initial effort towards #1250.
=> style: prefer imports from modules

.github/workflows/ci.yml, README.md, copier/main.py, copier/subproject.py, copier/template.py, copier/tools.py, copier/types.py, copier/user_data.py, copier/vcs.py, poetry.lock, pyproject.toml, tests/helpers.py, tests/test_dirty_local.py, tests/test_subdirectory.py, tests/test_tasks.py, tests/test_tools.py, tests/test_updatediff.py
I've dropped support for Python 3.7. Resolves #1251.
=> build: drop support for Python 3.7

copier/user_data.py, docs/configuring.md, tests/test_config.py
I've added a check that raises an error when a secret question has no default value. A secret question without a default value should have never worked although it did prior to Copier v8 because of some improper/incomplete answer validation. See https://github.com/copier-org/copier/issues/1177#issuecomment-1584879569 for some history on this topic.
As suggested in https://github.com/copier-org/copier/issues/1177#issuecomment-1585556997, the simplest yet effective solution is to require a secret question to have a default value.
Resolves #1177.
=> fix: require default value for secret question

copier/main.py, copier/template.py, docs/configuring.md, tests/test_output.py
I've added support for pre-copy and post-copy messages that can be written in plain text or markdown. Messages can be written inline or included via Jinja includes, and messages are rendered.
I'll work on pre-update and post-update messages in a separate PR once we've clarified whether the implementation in this PR is good.
Closes #723.
=> feat: add support for pre-copy and post-copy messages

docs/configuring.md, docs/creating.md, docs/faq.md, docs/generating.md
I've unified the linking to pages to [use relative paths to Markdown files](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages) instead of relative URL paths like `../<page name>` which is quite unintuitive because of the leading `../` that is needed as MkDocs page URLs have a trailing `/`.
=> docs: use relative path to Markdown file for page linking

copier/main.py
Updating involves some low-level git-fu. This can cause unpredicted files to get updated, and the report to the user sometimes is fake.
It'd be great to tell the truth, but for now at least let's just not lie.
Fix https://github.com/copier-org/copier/issues/943.
=> fix: don't lie about updated files

copier/cli.py, copier/main.py, copier/subproject.py, tests/test_tmpdir.py
Until now, Copier always left a lot of garbage in the tmp dir.
When running in batch, this could become a big problem, as templates would fill up memory (`/tmp/` is usually mounted as tmpfs).
@moduon MT-3411
=> fix: clean up tmp dir

docs/comparisons.md, docs/configuring.md, docs/creating.md, docs/faq.md, docs/generating.md, docs/updating.md
I've updated the docs to use autorefs for section references instead of (page links with) anchors. See the preceding discussion on this topic starting at https://github.com/copier-org/copier/pull/1258#issuecomment-1644936923.
Follow-up of #1258.
=> docs: use autorefs for section references

poetry.lock
I've updated the locked version of `setuptools` to the most recent one as #1295 seems to fail because of a problematic downgrade of `setuptools`.
=> build(deps-dev): bump setuptools from 66.0.0 to 68.1.2

copier/main.py, copier/template.py, docs/configuring.md, tests/test_output.py
I've added support for pre-update and post-update messages that can be written in plain text. Messages can be written inline or included via Jinja includes, and messages are rendered.
This (simple) implementation became possible due to #1156 since there's no output of an internal copy call of the update algorithm anymore. Without this copy call output suppression, the internal copy call would print the pre-copy/post-copy messages in case they are configured which we wouldn't want to see when running an update.
Related to #723. Follow-up of #1194.
=> feat: add support for pre-update and post-update messages

docs/configuring.md, docs/updating.md
I've updated some outdated examples showing `copier update --force` which isn't available anymore since v8.0.0.
Fixes #1299.
=> docs: update outdated `copier update --force` examples

.github/workflows/flakehub-publish-tagged.yml, README.md
This allows flake installers to get SemVer-compatible upgrades with no effort. Cool!
=> feat: release on FlakeHub.com too

copier/main.py, copier/subproject.py, copier/template.py, copier/vcs.py, tests/test_vcs.py
Fix gh-312.
There are several ways of doing this, I picked one that I considered simple enough. The idea is to always import `git` from a centralized place, and in that place do a soft fail if `git` fails to be imported from `plumbum.cmd`.
This is how `copier --version` looks like with these changes:
```
root@885f691c5e79:/# which git || echo "git is not available"
git is not available
root@885f691c5e79:/# copier --version
/usr/local/lib/python3.10/site-packages/copier/vcs.py:25: UserWarning: git command not found, some functionality might not work
warnings.warn(
copier 7.1.0a0.post98.dev0+5d600ff
```
On the other hand, I made `copier.vcs.is_git_bundle` more consistent with `is_git_shallow_repo` and `is_in_git_repo`, and now it returns `False` if there is an `OSError` or …
=> Do not immediately fail if git is not available

copier/template.py, copier/vcs.py, tests/test_recopy.py
Before this patch, when doing a recopy for a subproject previously placed on a git ref that was no longer reachable, the recopy process still tried to clone the old template.
The funniest part is that it was only trying to clone it while doing the process of cleanup. Thus, even if that clone worked, it was a waste.
This should make recopy more resilient and performant.
=> fix(recopy): never clone old template (even less if it's just for cleanup)

docs/configuring.md
A minor follow-up of 448455239ffb5c28ce48c07c70d50e1abf5fc215 that unifies terminology regarding the templates suffix (vs. "extension", which might be confused with Jinja _extensions_).
=> docs: unify terminology

copier/cli.py, docs/configuring.md, tests/test_unsafe.py
I've updated the return code for `UnsafeTemplateError` errors to use 4 (`1 << 2` / `0b100`) instead of 2 which is used by Plumbum already for `SwitchError` type errors.
Technically, this is a breaking change :thinking:, but I anticipate hardly anybody relying on the return code. WDYT, @copier-org/maintainers?
Fixes #1328.
=> fix(cli): use return code 4 for unsafe template error

copier/cli.py, docs/configuring.md, tests/test_cli.py
Users should be able to pass CLI data arguments and use a `--data-file` at the same time.  Let's just take inspiration from the [helm values file](https://helm.sh/docs/chart_template_guide/values_files/) and give highest priority to data values passed at the command line.
from the helm doc site:
>The list above is in order of specificity: values.yaml is the default, which can be overridden by a parent chart's values.yaml, which can in turn be overridden by a user-supplied values file, which can in turn be overridden by --set parameters.
=> feat: allow overriding data file with CLI arguments

docs/configuring.md
Some docs improvements in the `--data-file` flag section in `configuring.md`:
* Minor spelling/punctuation fixes
* A terminology fix for consistency and clarity: "data file" instead of "answers file" as the latter refers to the `.copier-answers.yml`
Follow-up of #1332.
=> docs: fix spelling/punctuation/terminology

copier/tools.py, copier/user_data.py, tests/test_copy.py
I've fixed the answer validation for `type: str` questions. Copier does loose parsing/validation, i.e. non-string values that can be interpreted as strings are valid, but the loose parsing/validation has been too loose. For instance, values such as `object()` or `{}` or `[]` were considered valid.
I've created a custom validator/parser inspired by [Pydantic's `str_validator`](https://github.com/pydantic/pydantic/blob/3b297adf6132636646f36e77a5cd2aacd6b4f03b/pydantic/v1/validators.py#L59-L77) which makes more sense IMO.
WDYT?
=> fix: fix answer validation for `type: str` questions

copier/cli.py
I've removed dead code that was meant to generate `--help-all` output in the API reference. It was shown in the [docs until v6.0.0](https://copier.readthedocs.io/en/v6.0.0/reference/cli/#copier.cli) but then disappeared. Do you happen to know why, @pawamoy?
=> docs: fix generating `--help-all` output in CLI reference

.readthedocs.yml
I've (hopefully) fixed the recent Read the Docs build error introduced by #1349. :crossed_fingers:
Fixes #1357.
=> docs: fix Read the Docs build

mkdocs.yml
Closes #1364.
I preferred explicitness.
=> docs: Use `pymdownx.highlight` instead of `codehilite`

copier/cli.py
I've added a missing type hint in `cli.py`.
=> build(typing): add missing type hint

docs/comparisons.md
I've added a footnote in the comparison on template updates for Cookiecutter that refers to [Cruft](https://github.com/cruft/cruft) as a tool that uses Cookiecutter to enable updates. I think Cruft should be mentioned for a fair comparison.
=> docs: mention Cruft for Cookiecutter in comparison on template updates

.github/workflows/ci.yml, poetry.lock, pyproject.toml, tests/test_updatediff.py
A basic pull request adding Python 3.12 to tested versions as well as proper PyPI classifiers for Python 3.12 support advertisement.
No functional changes
=> build: test and advertise Python 3.12 support

copier/tools.py
Closes #1378 
Not sure how to test this.
=> fix: Only fix Windows console with Colorama

copier/user_data.py, docs/configuring.md, tests/test_prompt.py
This PR is a sequel to https://github.com/copier-org/copier/pull/1049, taking into account review comments and https://github.com/copier-org/copier/issues/750 design proposal.
This PR only include the `multiple: true` form as the advanced form needs more specification and design I think, and it mostly relies on https://github.com/RhetTbull/questionary-superprompt#multiple-option which is not part of questionary.
However, it remains compatible as it is possible to add the advanced part later.
WDYT ?
=> feat(choices): support questionary checkbox for multiple choices using `multiple: true`

.github/workflows/ci.yml
This addresses an issue in macOS builds may be impacting caching. The command `sha256sum` which doesn't exist in `macOS-latest` is replaced with `shasum -a 256` which is present in both `ubuntu-latest` and `macOS-latest`
Closes #1389
=> fix(actions): swap sha256sum for shasum -a 256

copier/template.py, copier/tools.py
Closes https://github.com/copier-org/copier/issues/1402
=> fix: Address deprecation warning in `shutil.rmtree(onerror=...)`

copier/main.py, tests/test_updatediff.py
a file in the template but gitignored in the project should persist in the filesystem
fixes #1162
=> gitignored file

docs/faq.md
Fixes https://github.com/copier-org/copier/issues/1414 by documenting a clearer and safe alternative that covers most cases.
=> docs: explain how to use computed variables, more clearly

copier/main.py, tests/test_exclude.py
I've fixed a bug related to skipping excluded files, which may even contain malformed Jinja syntax. Before, Copier determined whether a file is skipped _after_ rendering it, which failed when the file contained malformed template syntax. Since the file should have been skipped, rendering should not have been attempted at all, so even malformed template syntax should not have mattered. Now, skipping excluded files happens _before_ a rendering attempt, so even malformed template syntax in excluded files is allowed.
This problem came up in a slightly different scenario where `copier.yml` contained `_envops` settings with Jinja statement markers, `_templates_suffix: ""`, and no subdirectory was configured, so that `copier.yml` was attempted to be rendered before the exclusion logic would have …
=> fix: skip excluded paths before rendering

tests/test_exclude.py
I've split a bundled test related to the [`_exclude`](https://copier.readthedocs.io/en/latest/configuring/#exclude) and [`_subdirectory`](https://copier.readthedocs.io/en/latest/configuring/#subdirectory) settings into individual tests.
Follow-up of https://github.com/copier-org/copier/pull/1440#discussion_r1409640778.
=> test(exclude): split bundled test into individual tests

copier/main.py, docs/configuring.md, docs/updating.md
I've replaced all non-code occurrences of the word "questionary" by "questionnaire" except in `CHANGELOG.md`.
Follow-up of #1430 for consistency.
=> docs: prefer "questionnaire" over "questionary"

.editorconfig, .github/workflows/ci.yml, .vscode/extensions.json, .vscode/settings.json, copier/cli.py, copier/main.py, copier/tools.py, copier/vcs.py, flake.lock, flake.nix, pyproject.toml, tests/test_config.py
Ruff is faster, better integrated, easier to configure... Cool!
Taplo also helps with toml maintenance.
=> build(lint): switch over to ruff; add taplo

docs/updating.md
- there was a inconsistence between the inline and rej default. as it's inline I changed the value in the corrected section
- as users won't need the 2 options at once, I split the 2 hooks.
=> docs: improve updating pre-commit documentation

poetry.lock, pyproject.toml
To do so, it required to add the `python_version < 4` marker to dependencies that still use upper bound markers.
I opened https://github.com/mtkennerly/dunamai/issues/74 to the only relevant one. In the case of poetry-dynamic-versioning, it's just a build-time dependency, so I don't really care it has that marker, as long as I build using Python 3.
=> build(deps): bump jinja

copier/template.py
Fixes https://github.com/copier-org/copier/issues/1186
=> fix: don't fail in systems with windows 1252 encoding

copier/tools.py, devtasks.py, pyproject.toml, tests/test_copy.py
what is says on the tin
- reduces the scope of mypy errors
- prevents accidentally 'hiding' new errors due to blanket lint suppression
=> add 'pygrep' lint group

copier/main.py, tests/test_exclude.py
I've fixed a regression introduced by #1440 which broke excluding files via `_exclude` for templated file paths. The problem was that the exclude matcher was applied to the templated and not yet rendered file path.
Fixes #1504.
=> fix(exclude): apply exclude matcher to rendered path

copier/cli.py, poetry.lock, pyproject.toml
besides removing an unneeded dependency (always good), using a 'native' decorator function allows for creating a fully-typed decorator
- decorated methods are now fully type annotated
- unblocks enabling stricter mypy configuration
- helps solve the errors in #1506...
=> remove 'decorator' dependency

copier/main.py, copier/user_data.py, pyproject.toml
adds the 'complexity' lint group to the ruff config.
I believe this brings the ruff config inline with the flake8 config, and therefore makes the flake8 linting redundant.
for reference, the flake8 config is:
```ini
[flake8]
ignore = E203, E501, W503, B950
max-line-length = 88
select = C,E,F,W,B
per-file-ignores=
__init__.py:F401
```
=> style: add 'complexity' lint group to ruff config

copier/user_data.py, tests/test_copy.py
I've fixed &ndash; because I consider it a bug &ndash; the order of choice items in answers to multi-select choice questions.
Consider this `copier.yml` example:
```yaml
python_versions:
type: str
help: Which Python versions would you like your project to support?
choices:
- "3.8"
- "3.9"
- "3.10"
- "3.11"
- "3.12"
multiselect: true
```
When passing the answer via API, e.g.
```python
copier.run_copy(src, dst, data={"python_versions": ["3.12", "3.10", "3.11"]})
```
then the answer is currently recorded as `["3.12", "3.10", "3.11"]`. IMHO, the recorded answer should be `["3.10", "3.11", "3.12"]` though. When using interactive prompting, then the answer is guaranteed to preserve the order from the `choices` list in `copier.yml`, so interactive prompting and API may not lead to identical …
=> fix: preserve choices order in answers to multi-select choice questions

copier/template.py, tests/test_config.py
I've fixed loading `copier.yml` with empty YAML documents. The fix is simple: `yaml.load_all()` returns a sequence of YAML documents, and empty documents are represented by `None`, so I'm filtering `None` items using `filter(None, yaml.load_all(...))`. [`filter(None, <sequence>)` actually filters any falsy items](https://docs.python.org/3/library/functions.html#filter) – not only `None`s –, but that's no problem in this case.
Before, Copier raised an error
```
TypeError: 'NoneType' object is not subscriptable
```
which is not very helpful for debugging. Now, an empty YAML document is simply ignored. Of course, there's little sense in having empty YAML documents, but it's easy to have one unintentionally, e.g. when the file ends with the `---` marker:
```yaml
question:
type: str
--- …
```
=> fix: ignore empty YAML documents in `copier.yml`

copier/main.py, copier/user_data.py, tests/test_copy.py, tests/test_prompt.py
I've added support for validating answers of multi-select choice questions. While `select` prompts (Copier single-select choice questions) only support per-choice validation, [`checkbox` prompts support answer validation](https://github.com/tmbo/questionary/blob/c894eeffbeb2f1448a108163998ba95b72a8e32a/questionary/prompts/checkbox.py#L32) similar to `text` prompts. Implementation-wise, there's a difference between `text` prompt validation and `checkbox` prompt validation, as `text` prompt validation supports raising `prompt_toolkit.validation.ValidationError` exceptions in the `validate` callable while `checkbox` prompt validation requires the `validate` callable to return an error message string or `True` when the answer is valid. Fortunately, also `text` prompt validation supports this …
=> feat: add support for validating multi-select choice answers

copier/main.py
Just add a missing docstring.
Extracted from #1561
=> docs(main): add the missing `skip_answered` docstring

copier/cli.py, copier/main.py, docs/configuring.md, tests/demo_migrations/tasks.py, tests/test_migrations.py, tests/test_tasks.py
This PR add a `-T/--skip-tasks` flag allowing to skip template tasks execution.
Some known use cases I have:
- while testing my template, I want to be able to perform multiple rendering with the extensions actives but without running tasks (which may be slow or depending on connection...)
- when applying a template with some bootstrap tasks on an existing project, I want to be able to skip the bootstrap tasks because I know they will fail
- when applying a third party template that I trust, I want to only skip tasks for some reason (known to break, not compatible with the environment...)
Should fix #1415
=> feat(tasks): allow skipping tasks with the  flag

tests/test_templated_prompt.py
Just some minor cleanup: This file in the test template tree is not used. It probably originates from a copy & paste error.
=> test: remove useless file in test template tree

tests/test_config.py
I've done some minor refactoring in the test suite: We now reuse the `git_init()` helper from `tests/helpers.py` in `tests/test_config.py` and I've deleted its duplicate in `tests/test_config.py`.
=> test: reuse `git_init()` helper

copier/main.py, tests/test_updatediff.py
I've stumbled over some suboptimal updating UX when _both_ the template and the project add the _same_ new file where the update algorithm would delete file content added by the project but not present in the template. This PR aims to improve the UX by yielding merge conflicts instead which seems semantically more correct than simply deleting previous project content.
The problem originates from the diff between the fresh project based on the old template and the actual project which includes a "new file mode" patch for any file added by the actual project, which gets applied to the same new file added to the project as part of rendering the new template on top of the project:
https://github.com/copier-org/copier/blob/813c90335276320a17c964a2cd4d4e91d89d8662/copier/main.py#L896-L906
My …
=> fix(updating): yield merge conflict when both template and project add same file

copier/user_data.py, tests/test_templated_prompt.py
I've fixed a bug related to rendering templated list items which was discovered when trying to template an item in the default value list of a multi-select choice question (see #1594). The root cause was not directly related to rendering the default value but rather caused by the `Question.render_value()` method passing any non-string value through. To resolve this problem fundamentally, I've extended the `Question.render_value()` method to recurse into a list and render each list item individually. I think we should add support for recursing into a `dict` in a follow-up PR and, thus, add support for rendering even deeply nested value in YAML data (e.g. actual, i.e. non-string, YAML choice items and default values to `type: yaml` questions).
Fixes #1594.
=> fix: render `default` list items for multi-select choice questions

copier/main.py, tests/test_copy.py
If _render_allowed identifies identical source and target, then only returns True if the path refers to a directory, not a file.
=> Do not overwrite identical files

docs/updating.md
I've followed the [official documentation _Preventing Commit of Merge Conflicts_](https://copier.readthedocs.io/en/stable/updating/#preventing-commit-of-merge-conflicts).
When I've tried to commit a `.rej` file, `pre-commit` complains that a key is missing:
```
❯ git commit                                                                                                           
An error has occurred: InvalidConfigError:                                                                          
==> File .pre-commit-config.yaml                                                                                    
==> At Config()                                                                                                     
==> At key: repos …
```
=> fix: Fixes documentation for pre-commit update rule for '.rej' files

.github/workflows/ci.yml
`macos-latest` has been bumped from macOS 12 (x86_64-based) to macOS 14 (ARM-based). Yesterday, macOS 14 didn't offer binaries for Python 3.8 and 3.9, which led to #1604. But it seems GitHub has added those binaries now. Yet our CI checks now run on heterogeneous runner architectures: x86_64 for Linux/Windows and ARM for macOS. Our current cache key does not contain the runner architecture, so  files built for x86_64 might be restored on the ARM runner until that cache gets updated with files built for ARM. So, I've added the architecture of the runner to the cache key which should fix immediate issues and make us more robust against similar changes in the future.
While at it, I took the opportunity to reformat the cache keys to use a - separator, which seems more common according to …
=> ci: add runner architecture to cache key

copier/main.py
Included a helpful error message to debug faster
Fixes #1436
=> handled error message correctly

docs/updating.md
I'm a fairly experienced user of Git (on the command line), but I found myself struggling after running `copier update` several times. I can't imagine how developers feel that are not fluent with Git.
A few hints in the docs may do wonders, I thought.
Mentioning failing commands and their error output makes sense, IMHO, as it helps developers recognize their particular situation. It may also help to drive relevant organic search traffic to the Copier documentation.
=> Add information on aborting an update to docs

docs/updating.md
As discussed in https://github.com/copier-org/copier/pull/1668#discussion_r1648990816:
Fixes the broken markup by using HTML entities.
In addition, I used slanted font (emphasized) for the error messages to make it clearer how to interpret the text.
=> docs: Fix ineffective escaping, emphasize error messages

poetry.lock
When updating any of the packages managed as a dependency by Poetry, you currently get this warning:
```
Updating dependencies
Resolving dependencies... (0.4s)
Warning: The locked version 2.32.0 for requests is a yanked version. Reason for being yanked: Yanked due to conflicts with CVE-2024-35195 mitigation
No dependencies to install or update
Writing lock file
```
This change hence updates the `requests` package (2.32.0 ➜ 2.32.3) to fix the issue.
=> chore: Update dependency requests (yanked, related to CVE-2024-35195)

.github/workflows/ci.yml, CONTRIBUTING.md
This is another approach to fix the same problem as https://github.com/copier-org/copier/pull/1641 by just letting the CI reformat and push back changes to the origin branch.
=> ci(pre-commit): auto-fix style problems

CONTRIBUTING.md, devtasks.py, poetry.lock, pyproject.toml
Reduces the code in the `devtasks` module replacing cleanup activity code by integrating [pyclean](https://pypi.org/project/pyclean/) in the development toolchain. PyClean is a tool focused on cleaning up Python bytecode and build artifacts.
<details>
<summary>`poetry install --with dev` (click to show output)</summary>
```console
$ poetry install --with dev
Installing dependencies from lock file
Package operations: 33 installs, 0 updates, 0 removals
- Installing distlib (0.3.7)
- Installing exceptiongroup (1.1.0)
- Installing filelock (3.13.0)
- Installing iniconfig (2.0.0)
- Installing platformdirs (3.11.0)
- Installing pluggy (1.5.0)
- Installing setuptools (68.1.2)
- Installing tomli (2.0.1)
- Installing cfgv (3.3.1)
- Installing coverage (7.0.5)
- Installing execnet (2.1.1)
- …
```
=> chore: Use pyclean to reduce custom developer tooling

copier/cli.py, tests/test_tasks.py, tests/test_unsafe.py
Couldn't get the `--skip-flags` option working until I passed the option to the worker.
=> fix: Missing passing of `skip_tasks` flag

.github/workflows/update-flake-lock.yml
Just a minor enhancement to avoid non-conventional commits in the `master` branch when squash-merging `flake.lock` update PRs (see https://github.com/copier-org/copier/pull/1699#issuecomment-2233840071 :see_no_evil:).
=> ci(flake): use commit message as PR title

copier/main.py, copier/vcs.py, tests/conftest.py, tests/helpers.py, tests/test_cli.py, tests/test_complex_questions.py, tests/test_conditional_file_name.py, tests/test_copy.py, tests/test_demo_update_tasks.py, tests/test_dirty_local.py, tests/test_legacy_migration.py, tests/test_migrations.py, tests/test_minimum_version.py, tests/test_output.py, tests/test_prompt.py, tests/test_subdirectory.py, tests/test_symlinks.py, tests/test_templated_prompt.py, tests/test_tmpdir.py, tests/test_tools.py, tests/test_unsafe.py, tests/test_updatediff.py, tests/test_vcs.py
I've fixed a problem that caused Copier to fail when Git didn't know the user identity (e.g. via system/global `user.{name,email}` settings) while generating a project based on a dirty template.
The problem was caused by a `git commit` call happening during the `copier.vcs.clone()` call on a dirty template:
https://github.com/copier-org/copier/blob/78c484379804bfdd20a652e2ebb5e5c940b9b828/copier/vcs.py#L192-L200
When the user identity wasn't known to Git, it failed with the following error:
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```
Instead of setting `user.{name,email}` before …
=> fix: support Git config without user identity

copier/main.py, copier/tools.py, docs/configuring.md, docs/updating.md, tests/test_tools.py, tests/test_updatediff.py
~~Previously, paths that matched a pattern in `skip_if_exists` and that were deleted in the generated project were recreated during each update.~~
~~These deletions are contained in the diff between old vanilla generated project and the (pre-update) current one. They are not executed though since the paths are excluded from the diff application.~~
Previously, if a file that was deleted intentionally in a generated project was changed in the template, an update would have regenerated it (but not if it did not have any changes).
This patch ensures that update behavior is consistent for paths that are not listed in `skip_if_exists` - don't regenerate deleted paths during `update` - by acquiring a list of deleted paths and excluding them in the copy operations that are relevant for acquiring …
=> fix(updating): exclude deleted paths on update

copier/user_data.py, tests/test_copy.py, tests/test_prompt.py
I've fixed the answer validation to apply also to secret questions. This problem came up in an internal discussion with a colleague who stumbled over secret questions not being validated.
In general, I see no reason why answers to secret questions should not be validated. Secret questions are a special case regarding project updates though. We require a secret question to have a default value because we need _some_ value to exist for replaying a fresh project based on the old template using the recorded answers, which don't include secrets. For this to continue working, it's crucial that the default value of a secret question passes the validator – but this rule should actually apply to all questions because otherwise `copier copy --defaults ...` would be useless. Just saying.
=> fix: validate answers to secret questions

copier/main.py, tests/test_recopy.py, tests/test_updatediff.py
I've fixed a bug where a recopy/update with `-A, --skip-answered` did not parse a new answer passed via `-d, --data`. The solution was simple: Skipping a question because of `-A, --skip-answered` needs to happen _after_ parsing a new answer via `-d, --data` takes place, so that using the new answer takes precedence over skipping it.
Fixes #1728.
=> fix: parse new answer when `--skip-answered` is used

docs/faq.md
Fixes https://github.com/copier-org/copier/issues/466
=> docs(git): tell how to pass HTTPS credentials

docs/updating.md
Document how to update when changing a multiselect base answer
The documentation to update, changing only one answer  when the question is a multi-select base choice, is missing.
This is from https://github.com/copier-org/copier/issues/1474#issuecomment-2328522026, but it also indicates to create the `.yaml` file in another directory (to avoid error `Destination repository is dirty; cannot continue. Please commit or stash your local changes and retry.`).
=> Document how to update when changing a multiselect base answer

.github/workflows/ci.yml, .readthedocs.yml, README.md, copier/main.py, copier/tools.py, copier/types.py, poetry.lock, pyproject.toml, tests/test_symlinks.py
I've dropped support for Python 3.8, as it reached its [EOL on October 7, 2024](https://devguide.python.org/versions/#unsupported-versions). 
The cleanup to reduce technical debt involves two ~breaking~notable changes because we're now using features only available on Python 3.9+:
- Use `pathlib.Path.readlink` and remove our custom compatibility function
- Use `typing.Annotated` instead of `typing_extensions.Annotated`, and remove the runtime dependency on `typing-extensions`
@copier-org/maintainers ~Should we make another release prior to merging this PR? And should we consider the changes in this PR non-breaking because Python 3.8 has reached EOL and shouldn't be used anymore?~ On second thought, I think none of the changes should be considered breaking because (a) an EOL Python version …
=> refactor: drop support for Python 3.8

poetry.lock
Just a simple
```shell
poetry lock
```
lock file update, as Dependabot doesn't do it for us.
=> build(deps): update lock file

copier/main.py, copier/tools.py, tests/test_exclude.py
I've fixed the filtering of files and directories with exclude patterns. Before, a negative exclude pattern was ignored when some parent path matched the exclude patterns. The reason lies in the custom top-down filesystem walk implemented in `Worker._render_folder()` which didn't traverse the contents of a directory if an exclude pattern matched while a _negative_ exclude pattern also matched a child of this directory.
The solution is based on a different approach to walking the filesystem and excluding paths. Now, an iterator of all paths (files and directories) in the tree rooted at the template's copy root is produced via a recursive extension of `os.scandir()` and then filtered with the exclude patterns, so a subtree isn't pruned during the top-down tree walk. Instead, every path in …
=> fix(exclude): support negative exclude matching child of excluded parent

copier/main.py, copier/tools.py, tests/test_symlinks.py
=> Support preserve_symlinks=False for directories

copier/user_data.py, docs/configuring.md, tests/test_copy.py, tests/test_templated_prompt.py
I've added support for dynamic choices by allowing a templated string value for the `choices` key that renders as valid YAML. All choice styles are supported. See also https://github.com/orgs/copier-org/discussions/1193#discussioncomment-10040365.
Resolves #1746 #1193.
=> feat: add support for dynamic choices

README.md
Hello Copier team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Copier Guru](https://gurubase.io/g/copier) to Gurubase. Copier Guru uses the data from this repo and data from the [docs](https://copier.readthedocs.io/en/stable/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Copier Guru" badge, which highlights that Copier now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …
=> Introducing Copier Guru on Gurubase.io

copier/main.py, tests/test_updatediff.py
Closes #1763.
**Please squash when merging, do not rebase.**
=> fix: Don't mark files without conflict markers as unmerged

copier/main.py, tests/test_recopy.py, tests/test_updatediff.py
I've fixed the update algorithm to always re-compute computed values in low-level `copy` calls, which fixes #1779 as side effect.
=> fix(updating): don't validate computed values

copier/tools.py
fixes https://github.com/copier-org/copier/issues/1837 by using pathlib logic to get an absolute path
info @wt-io-it
=> fix: get_git_objects_dir compatible with git 2.30.2

renovate.json
I've re-configured Renovate to use the semantic commit type `build` for all commits. The previous setting was behaving differently than I thought. I thought `fix` would only be used when also the manifest was updated, but it turns out that any runtime dependency updates would use `fix`. This is not desirable when maintaining a _library_ because lock file updates shouldn't be communicated to the users in the changelog. Thus, I've removed the previous configuration and added an override preset to use `build` for all updates.
=> build(renovate): configure semantic commit type `build`

docs/creating.md, mkdocs.yml
* Restructures documentation about available context variables.
* Adds (semi-)undocumented ones (`_copier_python`, `_folder_name`, `_copier_conf.os`).
Following [a request](https://github.com/copier-org/copier/pull/1733#discussion_r1836593276) by @sisp, this is extracted from https://github.com/copier-org/copier/pull/1733, which motivated the new structure for clarity.
Ref: https://github.com/copier-org/copier/issues/1842
=> docs: Restructure context vars, add undocumented ones

renovate.json
Just a minor Renovate config fix to make it use the semantic commit type `build` instead of `chore`/`fix` which included in `config:recommended` via `:semanticPrefixFixDepsChoreOthers`. It turns out that #1832 was incorrect because `:semanticCommitType(build)` is a preset for a setting, but `:semanticPrefixFixDepsChoreOthers` is a preset for _package rules_, so overriding those package rules requires a _package rule_ (preset) – at least that's how I understand it. `:semanticCommitTypeAll(build)` is exactly this. See also https://github.com/renovatebot/renovate/discussions/8440.
=> build(renovate): fix configuring semantic commit type `build`

copier/main.py, tests/test_updatediff.py
=> fix: don't crash when file is removed from a templated `.gitignore`

CONTRIBUTING.md, README.md, docs/configuring.md
A small change in the docs to support the use of `uv tool` instead of `pipx`, as it is sensibly faster and not many know about it.
=> docs:mention `uv tool` as an alterative to `pipx`

copier/errors.py, copier/jinja_ext.py, copier/main.py, docs/comparisons.md, docs/configuring.md, docs/creating.md, docs/reference/jinja_ext.md, mkdocs.yml, tests/test_dynamic_file_structures.py
What I did:
- Added a new Jinja extension in `copier/jinja_ext.py` to handle `yield` tags
- This is a lightweight extension that detects `yield` tags and sets up the necessary context through `jinja_env`
- Updated `_render_path` to return multiple destination paths and their corresponding contexts when `yield` tags are present
- Internally, delegated the recursive logic for generating paths and contexts from `yield` tags to the `_render_parts` function
- Added `extra_context` parameter to `_render_file` to enable injection of contexts generated from `yield` tags
=> feat: add dynamic file structures in loop using yield-tag

copier/errors.py, copier/main.py, copier/settings.py, copier/user_data.py, docs/configuring.md, docs/reference/settings.md, docs/settings.md, mkdocs.yml, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_config.py, tests/test_settings.py, tests/test_unsafe.py
Hello 👋🏼 
This PR adds support for user settings with initial support for:
- user defaults (#235)
- trusted repositories
Settings are stored in `<CONFIG_ROOT>/settings.yml` where `<CONFIG_ROOT>` is the
standard configuration directory for your platform:
- `$XDG_CONFIG_HOME/copier` (`~/.config/copier ` in most cases) on Linux as defined by
[XDG Base Directory Specifications](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- `~/Library/Application Support/copier` on macOS as defined by
[Apple File System Basics](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html)
- `%USERPROFILE%\AppData\Local\copier` on Windows as defined in
[Known …
=> feat(settings): add user settings support with `defaults` values and trusts

copier/subproject.py, tests/test_updatediff.py
I've fixed a string encoding/decoding bug on Windows that broke updating a project with recorded non-ASCII character answers.
According to my investigation, `pathlib.Path.read_text()` calls [`io.text_encoding()`](https://github.com/python/cpython/blob/aa845af9bb39b3e2ed08bbb00a8e932a97be8fc0/Lib/pathlib/_local.py#L776), and when no encoding value is provided (i.e., `encoding=None`) then a [default encoding is determined](https://github.com/python/cpython/blob/fc8c99a8ce483db23fa624592457e350e99193f6/Lib/_pyio.py#L56-L59). When I reproduced the error on a quite clean Windows 11, `sys.flags.utf8_mode == 0`, so `io.text_encoding(encoding=none)` returns `"locale"` and `locale.getencoding()` returns `"cp1252"`. At the same time, the [`to_nice_yaml` filter passes the serialized YAML string …
=> fix: decode answers file content explicitly as UTF-8

poetry.lock, pyproject.toml
I've dropped the `types-psutil` dev dependency, as it doesn't seem needed anywhere – `mypy` is passing locally for me without it being installed.
This PR will render #1971 obsolete.
=> build(deps): drop unused `types-psutil` dependency

copier/main.py, copier/types.py, copier/user_data.py, tests/test_config.py
I've reverted a change in #1880 that broke context manipulation via `copier-templates-extensions`. As part of #1880, we [extended the `copier.user_data.AnswersMap` to include additional Jinja context](https://github.com/copier-org/copier/pull/1880/files#diff-51a5fc56dc37de31d15f74ed1458469179fe72a8b697cbbc83b2a8e8e508f90bL455-R505) like `_copier_*` variables, which was called _system render context_. With this change, the Jinja context for rendering questions did not only include (previous) answers [but also system render context variables](https://github.com/copier-org/copier/pull/1880/files#diff-51a5fc56dc37de31d15f74ed1458469179fe72a8b697cbbc83b2a8e8e508f90bR510). Among those system render context variables is the [`answers_file` …
=> fix: expose only answers in question rendering context

copier/cli.py, tests/test_cli.py
Previously, the file specified with --data-file option were read with the system default encoding.
With this change, the binary stream is passed to PyYAML, and PyYAML detects the encoding automatically.
This ensures that UTF-8/UTF-16BE/UTF-16LE YAML files are read correctly, regardless of the system default encoding.
Fixes #1995
=> fix: read unicode-encoded file specified with --data-file

copier/main.py, copier/types.py, copier/user_data.py, docs/creating.md, tests/test_answersfile.py, tests/test_answersfile_templating.py, tests/test_copy.py, tests/test_migrations.py, tests/test_tasks.py, tests/test_templated_prompt.py
This PR exposes a `_phase` variable which can be one of `prompt`, `tasks`, `mmigrate` and `render`.
The known phases are grouped into the `copier.types.Phase` enum.
This implements #1883 and allows fixing copier-org/copier-templates-extensions#7
=> feat(context): expose a `_phase` context variable (fix #1883)

tests/test_legacy_migration.py, tests/test_minimum_version.py, tests/test_templated_prompt.py, tests/test_unsafe.py, tests/test_updatediff.py
This PR reduces the number of raised warning during tests:
- from 82 to 2 warnings on Python <= 3.11
- from 84 to 4 warnings on Python >= 3.12
To reduce those warnings, this PR:
- adds missing `pytest.warns()` context manager for expected warnings
- adds missing `pytest.deprecated_call()` on expected deprecation warnings
- migrate all tests containing migrations to the new migration format
Remaining warnings:
- 2 in `test_unsafe.py` on a remaining legacy migration test case (case only exists with legacy format)
- 2 `datetime.utcnow()` on Python 3.12+, tied to the deprecated built-in `now()`, adding a compatibility layer was not worth it given it will be removed
Benefits:
- tests expected warnings
- tests are up to date with the current API
- `pytest` output is uncluttered
This PR does not …
=> Reduce the number of test warnings

.github/workflows/ci.yml
I've updated the `JRMurr/direnv-nix-action` action to v4.2.0 which should resolve the problem of our failing Nix CI jobs:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v3.0.11`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
I requested a `v4` tag alias for `v4.2.0`, but the author hasn't responded yet, so I decided to use the full version for us to move forward.
=> build(deps): update `JRMurr/direnv-nix-action` action to v4.2.0

copier/user_data.py, tests/test_answersfile.py
I've fixed loading external data files to auto-detect the encoding instead of using the system's default encoding.
Without the fix, the added test fails with this error:
```
self = <yaml.loader.SafeLoader object at 0x7f20921b6e70>, size = 4096
def update_raw(self, size=4096):
>       data = self.stream.read(size)
E       UnicodeDecodeError: 'cp932' codec can't decode byte 0x98 in position 7: illegal multibyte sequence
```
Follow-up of #1973. Inspired by #1998.
=> fix: auto-detect encoding when reading external data file

tests/test_cli.py, tests/test_complex_questions.py, tests/test_legacy_migration.py, tests/test_migrations.py, tests/test_prompt.py, tests/test_recopy.py, tests/test_subdirectory.py, tests/test_templated_prompt.py, tests/test_unsafe.py, tests/test_updatediff.py, tests/test_vcs.py
I've improved the test suite to consistently use our helper function `copier.user_data.load_answersfile_data()` for loading answers. There are only a few exceptions where the answers file was written and read as JSON; changing those to YAML would slightly alter the semantics of the test.
=> test: use helper function to load answers file data

README.md, docs/generating.md
=> Document behavior of generating destination path when copying

copier/main.py, copier/types.py, docs/configuring.md, docs/creating.md, tests/test_context.py
* Makes `exclude` configuration templatable.
* Adds a `_copier_operation` variable to the rendering contexts for `exclude` and `tasks`, representing the current operation - either `copy`~~, `recopy`~~ or `update`.
* ~~Adds the (semi-)undocumented `_copier_python`, `_copier_conf.os` and `_folder_name` variables to the docs in a second commit (since I restructured them anyways)~~ ~~extracted into https://github.com/copier-org/copier/pull/1856, will rebase once it's merged~~ rebased
Notes:
This was proposed here: https://github.com/copier-org/copier/issues/1718#issuecomment-2282643624
I hope the way it's implemented and tested is as intended by @yajo. ~~The tests are quite synthetic,~~ I would expect the usual application to be `_copier_operation (!/=)= "update"`.
Fixes: …
=> feat: Add `_operation` variable

copier/main.py, tests/helpers.py, tests/test_exclude.py, tests/test_updatediff.py
It seems that this place was overlooked. The file encoding is specified on all other non-binary `open(...)` calls except for this one.
Closes #2006
=> Explicitly specify file encoding for windows

copier/main.py, copier/types.py, copier/user_data.py, tests/test_templated_prompt.py
I've restored access to the full rendering context (including, e.g., `_copier_conf.*`) in the prompt phase. For example, the following question specification is now valid:
```yaml
project_name:
type: str
default: "{{ _copier_conf.dst_path | basename }}"
```
Support for this feature was unintentionally added by #1880 merely as a side effect and released as v9.5.0. As it turned out, #1880 introduced a regression (#1977) which we fixed in #1993 by partially reverting #1880, released as v9.6.0. As a result, only answers (and external data) were accessible in the rendering context of the prompt phase (i.e., pre-v9.5.0 behavior). But some Copier template authors have already started using variables from the full rendering context in the prompt phase with v9.5.0, so v9.6.0 contains a breaking …
=> fix: restore access to full rendering context in prompt phase

docs/configuring.md
I was getting rather confused as to why the examples in the docs for `_external_data` were not working, after checking the tests it seems there was a typo
=> docs: Correct typo (broken _external_data example)

copier/errors.py, copier/main.py, tests/test_prompt.py
I've improved the error handling when prompting in a non-interactive environment, which was failing with `EOFError`. Now, the new `InteractiveSessionError` exception is raised.
Resolves #1988.
=> feat: raise `InteractiveSessionError` when prompting in non-interactive environment

copier/main.py, tests/test_recopy.py, tests/test_updatediff.py
I've fixed a bug that caused an update or recopy involving the switch of a question's `when` value from `when: true` to `when: false` to reuse the recorded answer, specifically for computed values the default value wasn't used to re-compute the answer. 
To fix it, we now delete the last answer of a `when: false` question.
Fixes #2057.
=> fix(updating): ignore last answer of `when: false` questions

copier/settings.py, docs/settings.md, tests/test_settings.py
platformdirs implicitely sets appauthor to appname if not explicitely set to false, resulting in an dir with <CONFIG_ROOT>/copier/copier
Closes https://github.com/copier-org/copier/issues/2070
=> fix: settings dir with deduplicated copier subdir

copier/cli.py, copier/errors.py, copier/main.py, poetry.lock, pyproject.toml, tests/test_cleanup.py
Introduce the TaskError exception to handle subprocess failures gracefully. 
solves #1990
=> ✨ Add TaskError exception for subprocess management

renovate.json
I've added the preset [`customManagers:githubActionsVersions`](https://docs.renovatebot.com/presets-customManagers/#custommanagersgithubactionsversions) to the Renovate config to support Renovate comments in GitHub Actions like:
```yaml
UV_VERSION: "0.6.13"
```
Follow-up of #2079.
=> build(renovate): add preset `customManagers:githubActionsVersions`

pyproject.toml, renovate.json, uv.lock
I've pinned the versions of dev-dependencies in `pyproject.toml` because:
- We control the exact version and can ensure compatible configuration. With lower-bounded versions, the dependency resolver may downgrade a dependency without us noticing unless we study the lock file changes diligently.
- We don't need to maintain an accurate version lower bound. Strictly speaking, if we declare a lower version bound – even for a development dependency –, we'd need to ensure that all versions that satisfy this constraint work. This is difficult and extremely cumbersome to achieve with, e.g., linters and formatters because different versions may result in different linting and formatting results. If we pin such development dependencies, we're not suggesting that a range of versions yields identical …
=> build(deps): pin versions of dev-dependencies in `pyproject.toml`

copier/settings.py
This is to avoid this warning with copier 9.7:
`.venv/lib/python3.13/site-packages/copier/settings.py:16: DeprecationWarning: Importing `OS` from `copier.tools` is deprecated. This module member is intended for internal use only and will become inaccessible in the future. If you have any questions or concerns, please raise an issue at <https://github.com/copier-org/copier/issues>`
=> Silence `copier.tools` deprecation warning

flake.nix, pyproject.toml, uv.lock
I've made some dev-dependencies (Ruff, Commitizen, Taplo) uv-managed instead of Nix-managed to
- make them available to contributors who don't have a Nix setup, and
- manage their versions explicitly instead of relying on the versions available on the Nix channel.
To use the same version of a tool everywhere, I've overridden the devenv pre-commit hooks with `package = null` and a custom `entry` that uses the executable in the Python virtual env. As it turns out, using impure Nix dev shells has some known issues with binary executables like `ruff` or `taplo` (see, e.g., https://github.com/astral-sh/ruff/issues/1699). To make them work, they must be patched with `patchelf`, which is something Nix performs internally as well when building binary packages. This is not perfect, but it feels …
=> build: use uv-managed dev-dependencies in Nix-managed pre-commit hooks

devtasks.py
I've fixed running linters in a `docker.io/nixos/nix` container. There were two problems:
- The `nix develop` command must be run in a shell, so I wrapped it in `bash -c 'nix develop ...'`.
- When running a non-rootless container, the current user in the container differs from the owner of the project files and directories. Git raises an error in this case unless `safe.directory = ...` is configured. Hence, I'm configuring Git globally to apply this setting only in the container context.
=> build: fix container-based linting in devtasks script

.github/workflows/ci.yml, .github/workflows/release.yml
I've migrated our release workflow from using PyPI access tokens to [trusted publishing](https://docs.pypi.org/trusted-publishers/).
A few remarks about advice on https://docs.pypi.org/trusted-publishers/security-model/ that I've followed:
* I've created a dedicated workflow `release.yml` that is trusted by pypi.org. But it seems that dependence on jobs from another workflow (here, `build` and `flake-check` from `ci.yml`) via `needs` isn't supported. The only alternative I've found is dependence on the completion and success of a complete workflow via [`workflow_run`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run) and `job.<job_id>.if: ${{ github.event.workflow_run.conclusion == 'success' }}`, but I haven't …
=> ci(release): migrate to PyPI trusted publishing

.github/workflows/release.yml
I've changed the release setup to upload to test.pypi.org also on the default branch (`master`) to test the publishing process more regularly (with some inspiration from [`github.com/iterative-ai/dvc:.github/workflows/build.yaml`](https://github.com/iterative/dvc/blob/99d9ca714de61518bd672ff647ed1ad7fb56f1d1/.github/workflows/build.yaml#L50-L73)).
=> ci(release): publish to test.pypi.org on pushing to `master` branch

.github/workflows/release.yml
Uploading distributions to PyPI fails when the version contains a local version identifier. For example:
```
Uploading distributions to https://test.pypi.org/legacy/
Uploading copier-9.7.2.dev12+gf82a0a5-py3-none-any.whl
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
Bad Request
```
This is, in fact, stated in [PEP 440](https://peps.python.org/pep-0440/#local-version-identifiers):
> Local version identifiers SHOULD NOT be used when publishing upstream projects to a public index server, [...]
Publishing test releases on pushing to the `master` branch doesn't require a local version identifier though, so I've added an override to omit it. The override can be applied …
=> ci(release): build distributions without local version identifier

.github/workflows/release.yml
I've fixed the override to omit local version identifiers when building distributions for publication on test.pypi.org. It turns out that `hatch-vcs` doesn't support all environment variables from `setuptools-scm`. :disappointed: The workaround is to patch `pyproject.toml` with the appropriate `hatch-vcs` setting that is passed through to `setuptools-scm`.
=> ci(release): fix building distributions without local version identifier

copier/_main.py
Fixes the stage order in which the git index gets updated on merge conflicts. This is a preparation PR for @pawamoy.
This change doesn't seem to break any tests, however im not familiar enough with the code base to write one that catches this condition.
fixes https://github.com/copier-org/copier/issues/2075
=> fix: correct git stage order on merge conflicts

docs/configuring.md
I've added missing documentation of the `skip_answered` setting.
=> docs: add `skip_answered` setting

copier/__init__.py, copier/_cli.py, copier/_main.py, copier/_tools.py, copier/_types.py, docs/configuring.md, docs/updating.md, tests/test_cli.py, tests/test_updatediff.py
Sometimes, a user might only want to update the answers to their questions, but not the template version.
As far as I am aware, copier does not support that currently.
In this PR, I add a `--answers-only` flag to `copier update` which fills exactly this gap.
Note about tests: I am a bit overwhelmed by your testing setup, could you maybe please point me to the right places to add corresponding tests? Thanks in advance!
Cc @pavelzw
=> feat: add `--vcs-ref=:current:` feature to reference the current ref when updating

copier/_main.py, copier/_user_data.py, docs/configuring.md, flake.nix, pyproject.toml, tests/test_answersfile_templating.py, uv.lock
More about codespell: https://github.com/codespell-project/codespell .
I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.
CI workflow has 'permissions' set only to 'read' so also should be safe.
TODOs
=> Add codespell support (config, workflow to detect/not fix) and make it fix some typos

renovate.json
I've updated Renovate's range strategy to `update-lockfile` for runtime and `pin` for dev dependencies. Previously, Renovate was bumping the pins of dev dependencies, but it didn't update the lock file for direct runtime dependencies (except when performing lock file maintenance). I think it's preferable to update direct dependencies in the lock file to (a) discover incompatibilities as early as possible and (b) receive isolated updates for better problem resolution.
=> build(renovate): use range strategy `update-lockfile` for runtime and `pin` for dev dependencies

copier/_main.py, copier/_types.py
I've fixed a regression introduced by #2023 which causes infinite recursion when accessing `_copier_conf.answers_file` via Jinja context hook with `copier-templates-extensions`.
When rendering the answers file path in [`Worker.answers_relpath`](https://github.com/sisp/copier/blob/263aa10fa7ef09152933721f2ec951d968a1d671/copier/_main.py#L617-L629), which is accessible in the render context as `_copier_conf.answers_file`, the render context also includes `_copier_conf.answers_file` as a lazy dict value of `_copier_conf`. That's no problem when simply rendering the answers file path exposed as `_copier_conf.answers_file` because the answers file template never uses this variable itself. But when a context hook accesses `_copier_conf.answers_file` (e.g. in …
=> fix: avoid infinite recursion when accessing `_copier_conf.answers_file` via Jinja context hook

.devcontainer/devcontainer.json, CONTRIBUTING.md
I've added support for setting up our development environment using a VS Code dev container. This is a quite common tool stack and integrates very nicely with Devbox, so users who use dev containers will have a pleasant experience without the need to install Devbox on the host.
=> chore: add VS Code dev container setup

copier/_user_data.py, docs/configuring.md, tests/test_cli.py, tests/test_copy.py
I've added support for providing serialized answers to multiselect choice questions.
This feature enables two use cases:
1. The default value can be templated by rendering default choice items as a YAML-style list.
2. An answer can be passed via the CLI flag `--data` as a YAML-style list. Resolves #1474.
The answer to a multiselect choice question is a list of choice items. While it seems that the most obvious solution is to parse the answer using a YAML parser, I think it's not the right approach because the list items should be parsed according to `type: <type>` and not necessarily using a YAML parser, and it's inconsistent with other question types to first parse them as YAML and afterwards parse according to `type: <type>`. But I've found a way to shallowly parse the serialized answer …
=> feat: add support for providing serialized answers to multiselect choice questions

.devcontainer/devcontainer.json
I've added the official VS Code extension for Devbox to the list of extensions installed in the dev container. It auto-activates the Devbox shell in VS Code's integrated terminal and replaces running `devbox shell` as a post-create command, which leads to random distortions when typing in the shell.
=> chore(devcontainer): add VS Code extension for Devbox

renovate.json
I've fixed the package name to `nodePackages.prettier` (which is the name used in the Nix registry) in the Renovate package rule.
Follow-up of #2225.
=> chore(renovate): don't update Prettier to v3.4.0+ (again)

copier/_vcs.py, tests/test_vcs.py
Without `-- .` on the end cause git to not checkout latest changes from **.git** directory.
[fixes #1887]
=> fix(vcs): git checkout after clone must contains `-- .`

.github/workflows/ci.yml
I just stumbled over a CI bug that has prevented testing against Python versions other than 3.9 for the past ~1 month. :see_no_evil: Since adding `.python-version` to declare the Python version to use for development of Copier, our matrix tests have been ineffective, as uv downloads the Python version specified in this file instead of using the Python interpreter found on the search path. For example, the `build (ubuntu-latest, 3.13)` job's log contains the following snippet:
```
Run uv sync --frozen
Downloading cpython-3.9.23-linux-x86_64-gnu (download) (28.3MiB)
Downloading cpython-3.9.23-linux-x86_64-gnu (download)
Using CPython 3.9.23
```
To fix this, I've added
```yaml
with:
python-version: ${{ matrix.python-version }}
```
to the `astral-sh/setup-uv` action config according to [uv's …
=> ci: override Python version from `.python-version` with matrix version

CONTRIBUTING.md, tests/conftest.py, tests/helpers.py, tests/test_complex_questions.py, tests/test_conditional_file_name.py, tests/test_output.py, tests/test_prompt.py, tests/test_templated_prompt.py, tests/test_updatediff.py
When running the tests for the repo on `gitpod.io`, I kept on running into failed tests due to timeout of the spawn from `pexpect`:
```bash
=================================================================================== short test summary info ====================================================================================
SKIPPED [1] tests/test_prompt.py:609: TODO: fix this
SKIPPED [1] tests/test_settings.py:30: Windows-only test
XFAIL tests/test_updatediff.py::test_update_needs_more_context[True-1] - Not enough context lines to resolve the conflict.
XFAIL tests/test_updatediff.py::test_update_needs_more_context[True-2] - Not enough context lines to resolve the conflict.
XFAIL tests/test_updatediff.py::test_update_needs_more_context[False-1] - Not enough context lines to resolve …
```
=> Make spawn timeout into a pytest argument to solve false negative in tests
