copier-org/copier

docs/usage.rst, requirements.txt, voodoo/dir_utils.py, voodoo/main.py, voodoo/script.py, voodoo/vcs.py
Still a WIP, requesting feedback.
=> Template dirs

README.md
I am not sure what the
```
---
```
was about. I think it was cruft. Removed it.
=> Removed cruft from yaml blocks

copier/main.py
Addendum to: https://github.com/jpscaletti/copier/issues/38
=> Expanduser on all paths

copier/main.py, copier/tools.py, copier/user_data.py
=> Providing output when running tasks.

tests/test_copy.py
Commit sufficiently explained through diff.
=> Improved name of test case

copier/config/factory.py, copier/config/objects.py, copier/config/user_data.py, copier/main.py, copier/tools.py, copier/types.py, copier/vcs.py, copier/version.py, tests/demo_invalid/voodoo.json, tests/test_config.py, tests/test_copy.py, tests/test_extra_paths.py, tests/test_tools.py
- Removed left-over `voodoo.json`
- Removed dead code
- Formatted code via `black`
- Formatted imports  via `isort`
- Removed empty test file `test_data.py`
=> Cleanups and formatting

copier/config/user_data.py, tests/test_config.py
Moved file existence check from `loader` function into `load_config_data`.
Result:
- DRYer code
- Only calling those functions actually needed to handle respective file format
=> Improvements to config file loaders

README.md, copier/config/objects.py, copier/config/user_data.py, mm.py, setup.cfg, tests/demo_json/copier.json, tests/demo_json/user_data.txt.tmpl, tests/demo_toml/copier.toml, tests/demo_toml/user_data.txt.tmpl, tests/test_config.py, tests/test_copy.py
... also improved loading mechanisms.
~~**WIP** Do not merge, yet.~~
@jpscaletti 
I consider this **PR** merge ready.
Please have a look and review it.
Closes: #65
=> Removed support for JSON and TOML config files.

copier/config/user_data.py, copier/tools.py
Minor changes for a more well-rounded code.
=> Improvements to config file related exceptions.

copier/config/user_data.py, tests/test_config.py
=> Basing config file identification on regex

copier/config/objects.py, copier/main.py, tests/demo/README.txt, tests/demo/README.txt.tmpl, tests/test_copy.py
Fix #91.
Includes one commit from #98 that can be removed when it's merged. It's for fixing travis.
=> Ignore $file if $file.tmpl exists

copier/main.py, tests/demo/[% if not py3 %]py2_folder[% endif %]/thing.py.tmpl, tests/demo/[% if py3 %]py3_folder[% endif %]/thing.py.tmpl, tests/test_copy.py
=> Skip files and folders if their names evaluate to ""

copier/tools.py, tests/test_updatediff.py
This way it will be more readable and it will produce less diff if the template copier.yml file is updated.
=> Sort answers file

copier/cli.py, tests/test_cli.py
A bug introduced in #121 made copier --help stop working.
Test added.
=> Fix copier --help

.github/workflows/ci.yml, copier/main.py, pyproject.toml, tests/test_updatediff.py
=> Supply the copier binary and install it in CI

copier/config/factory.py, copier/config/user_data.py, copier/main.py, tests/test_answersfile.py, tests/test_complex_questions.py
=> Grammar and spelling improvements

.github/workflows/ci.yml, .github/workflows/coverage.yml, copier/config/user_data.py, tests/demo_answersfile/copier.yml, tests/test_answersfile.py
Any other method, if it gets casted from `None` it will return the answer default.
In the case of `str`, `None` would default to `"None"`, which is not desired.
=> Use None instead of "None" for str answer defaults

README.md, pyproject.toml
=> Check readme

poetry.lock, pyproject.toml
=> Re-add module packaging

README.md, copier/config/user_data.py
As questions can include now a more detailed help and types, it would be helpful to have them more spaced. It looks better.
=> More space among questions

.github/workflows/ci.yml, .github/workflows/coverage.yml, .pre-commit-config.yaml, copier/__init__.py, copier/cli.py, copier/version.py, pyproject.toml
=> Dynamic versioning

copier/vcs.py, tests/test_vcs.py
Fixes https://github.com/Tecnativa/doodba-copier-template/issues/14
=> Fix shortcode without .git suffix

copier/main.py
Close #175 by supporting old git versions. These will provide a worse update experience, but still work. Instead of failing, a warning is printed for the user.
=> Do not die with old git versions

README.md
=> Recommend copier-template GH topic

.pre-commit-config.yaml, CHANGELOG.md, CONTRIBUTING.md, README.md
=> Update README structure

README.md, copier/config/factory.py, poetry.lock, pyproject.toml, tests/demo_minimum_version/copier.yml, tests/test_minimum_version.py
=> Add minimum copier version verification

CHANGELOG.md, README.md
=> Improve tasks & migration docs, prepare v3.1.0 release

README.md, copier/config/factory.py, poetry.lock, pyproject.toml
=> Remove semver

.github/workflows/ci.yml
Apply suggestion from https://github.com/actions/cache/issues/315#issuecomment-671424348.
=> Attempt to enable caching on Windows

mkdocs.yml
This will reduce friction while testing docs in PRs until https://github.com/pawamoy/mkdocstrings/issues/144 is fixed.
=> Make latest the default docs location

docs/configuring.md
Little bug that made these docs look like code instead of normal docs.
=> Fix admonitions

mkdocs.yml
Fixes some bugs introduced in #271 by mistake. That automerge bot was too fast.
=> Fix broken docs links

.gitpod.yml, README.md
Allow contributors to start hacking right away with a single click.
=> Configure gitpod

.gitpod.dockerfile, .gitpod.yml, .theia/settings.json, CONTRIBUTING.md
- Install basic development tools and configure them to work out of the box, based on gitpod's official ubuntu docker image.
- Make Fish shell available.
- Add some basic settings.
- Add instructions to CONTRIBUTING.
=> Fix gitpod configuration

docs/configuring.md, docs/updating.md
This is very cool and it doesn't seem to be clearly explained anywhere.
=> Explain how to use multiple templates for the same project

copier/config/user_data.py, tests/helpers.py, tests/test_prompt.py
When updating a project, a choice answer never got a good default value.
=> Fix wrong default choice

copier/tools.py, tests/test_prompt.py
Don't be so strict, because user input is sometimes unpredictable.
=> Allow more types when casting values as booleans

docs/configuring.md, docs/updating.md, poetry.lock, pyproject.toml
This keeps happening once and again, and confuses users.
Let's clarify it here in the docs.
I also fix some broken links and update deps BTW.
=> Advise users to never edit manually the copier answers file

copier/cli.py, copier/main.py
=> Fix typos in help & docstring.

copier/main.py, tests/test_copy.py
=> Ensure empty-named dirs work as expected

copier/cli.py, copier/errors.py, copier/template.py, copier/tools.py, copier/user_data.py, poetry.lock, pyproject.toml, tests/test_config.py
- Move template methods to template module.
- Remove load_config_data.
- Verification on lazy property.
- Add Template.min_copier_version.
=> Refactor a bit how version warnings are issued

.github/workflows/ci.yml, poetry.lock
I think it comes from this: https://github.com/python-poetry/poetry/issues/3663
=> ci: Stop using Poetry debug verbosity

.github/workflows/ci.yml, copier/main.py, copier/tools.py, copier/types.py, copier/vcs.py, poetry.lock, tests/test_tools.py
Issue #345
Draft to see how CI behaves.
=> Fix temporary directory removal on Windows

copier/errors.py, copier/main.py, copier/template.py, copier/tools.py, copier/user_data.py, docs/configuring.md, poetry.lock, pyproject.toml, tests/demo_extensions_additional/copier.yml, tests/demo_extensions_additional/super_file.md.jinja, tests/demo_extensions_default/super_file.md.jinja, tests/test_jinja2_extensions.py, tests/test_updatediff.py
=> feat: Add extensions option allowing to load additional Jinja2 extensions

.gitignore, .gitpod.dockerfile, .gitpod.yml, .pre-commit-config.yaml, .theia/settings.json, .vscode/extensions.json, .vscode/settings.json, CONTRIBUTING.md, devtasks.py, docs/configuring.md, poetry.lock, pyproject.toml
These days, Gitpod supports VSCode workspaces instead of only Theia.
Theia understands settings under `.vscode` as well as under `.theia`, but VSCode only understands settings under `.vscode`. Thus, it seems reasonable to move settings to that new location and then provide a good UX on both local VSCode and Gitpod's.
I also install new tools such as commitizen.
The goal is that just clicking on Gitpod badge, you have a full dev environment ready to hack.
=> Implement commitizen and improve VSCode/Gitpod UX

docs/configuring.md
All those new things were not documented... 🤦‍♂️
Fix https://github.com/copier-org/copier/issues/297
=> docs: update questionary configuration

.gitpod.yml, .vscode/extensions.json, .vscode/tasks.json, README.md, docs/comparisons.md, docs/configuring.md, docs/creating.md, docs/generating.md, docs/updating.md, mkdocs.yml
🤦‍♂️ it seems I forgot to document a lot of changes.
=> docs: update with latest changes

copier/main.py, copier/tools.py
=> refactor: Remove `__all__` variables from modules

CHANGELOG.md, copier/main.py, docs/configuring.md, tests/test_empty_suffix.py
=> fix: Handle empty templates suffix

copier/errors.py
As mentioned in another PR. It initially confused me, though it's not that bad. Your decision @Yajo :smile:
=> refactor: Remove extraneous parent classes from errors

CHANGELOG.md, copier/cli.py, copier/main.py, copier/user_data.py, docs/configuring.md, tests/test_answersfile.py, tests/test_complex_questions.py, tests/test_config.py, tests/test_copy.py, tests/test_demo_update_tasks.py, tests/test_empty_suffix.py, tests/test_migrations.py, tests/test_normal_jinja2.py, tests/test_output.py, tests/test_subdirectory.py, tests/test_tasks.py, tests/test_templated_prompt.py, tests/test_updatediff.py
=> feat: Add additional flags for using default questions or overwriting files

tests/test_updatediff.py
=> test: fix outdated prettier hook

.github/workflows/ci.yml, CHANGELOG.md, copier/errors.py, copier/main.py, docs/configuring.md, docs/creating.md, tests/demo_migrations/copier.yaml, tests/test_jinja2_extensions.py
Fixes issue #389
Any idea for a test :smile:? I guess I'll just run the filter in a template.
=> feat: Make the `to_json` filter support the conf object

README.md
=> docs: Add a quick start example on how to create a template

README.md, copier/cli.py, copier/errors.py, copier/main.py, copier/subproject.py, copier/template.py, copier/tools.py, copier/types.py, copier/user_data.py, mypy.ini, poetry.lock, pyproject.toml, tests/test_templated_prompt.py, tests/test_tools.py
It turns out that we were getting false positives in the tests that checked style and typing, so lots of those changes got accumulated.
Man, this mypy is hard...
=> fix(pre-commit): fix false positives and add missing typing

README.md, docs/comparisons.md, docs/configuring.md, docs/creating.md, docs/updating.md, mkdocs.yml, poetry.lock
Issue #521 
Changes are cleanly separated into several commits.
=> Docs enhancements

poetry.lock, pyproject.toml
=> build: Relax dependencies constraints (remove upper bounds)

CHANGELOG.md, copier/main.py, poetry.lock, tests/conftest.py, tests/test_updatediff.py
When a template gets updated and a file gets deleted within, subproject updates should delete that file automatically too.
Fix https://github.com/copier-org/copier/issues/461
=> fix: remove files on update

CHANGELOG.md
=> bump: new release

CHANGELOG.md
=> fix release data

copier/template.py, tests/test_copy.py
Fixes #675 
Create test with example tag (it fails), make the test pass - by checking one last time that we can parse a version out of the tag.
=> Better handle azdo style tags

copier/user_data.py, docs/configuring.md, poetry.lock, tests/conftest.py, tests/test_complex_questions.py
closes #398 and adds a `validator` field to `Question`
This PR pretty much just applies all the comments made by @yajo  in #698
I went with the name `validator`, which seemed to be what @yajo and @pawamoy gravitated to in the discussion of #398, which required renaming the pydantic import ... let me know if you prefer going with a different name.
will add tests, but posting now for feedback
=> feat: add validator field to Question

README.md
This PR adds an alternative install with Conda to the README.
=> Alternative install with Conda

CHANGELOG.md, CONTRIBUTING.md, README.md, docs/comparisons.md, docs/configuring.md, docs/creating.md, docs/generating.md, docs/updating.md
Just a few spelling fixes for correctness and consistency.
=> docs: fix spelling

docs/generating.md
=> clarify the --vcs-ref HEAD usage

copier/main.py, copier/template.py, tests/test_vcs.py
Closes #709
I implemented that on GitPod.io but have a lot of test failures due to pexpect timeouts, and `pkg_resources` module not being found (it seems the env on gitpod is kinda broken). Opening to see how CI behaves.
=> fix: Make sure to delete local temporary clones

copier/main.py, copier/template.py, copier/vcs.py, tests/test_vcs.py
=> Expand tilde

docs/configuring.md
=> docs: Add missing dash in CLI flag docs

docs/configuring.md
As requested in https://github.com/copier-org/copier/discussions/892
=> docs: add example of regular expression validator

copier/template.py
I've moved some code unrelated to a surrounding `try`/`except` block out of that block.
=> refactor: move unrelated code out of try-except block

flake.nix
Default to leverage our public binary cache.
=> build(flake): provide default nixConfig

docs/faq.md
Fix https://github.com/copier-org/copier/issues/955.
=> docs: clarify that you can use copier on preexisting projects

docs/configuring.md
Just a minor correction in the docs related to drawing a filesystem tree.
=> docs: fix filesystem tree

copier/main.py
Just a minor cleanup: I've removed an unused class method argument .
=> refactor: remove unused method argument

copier/main.py
Just some minor cleanup: I've deduplicated some code in `main.py::Worker._render_allowed(...)`.
=> refactor: deduplicate code

README.md
Copier has grown up. Let's say thanks. 😊
=> docs: time to update thankyouss!

copier/main.py
Just a minor cleanup: I've simplified the question answering logic a little by avoiding the unnecessary creation of a list of questions that shall be asked, i.e. for which no answers have been provided by the user via CLI/API.
=> refactor: simplify question answering

copier/__main__.py, copier/cli.py
Just a minor stylistic improvement to consistently use relative imports.
=> style: use relative imports consistently

tests/test_answersfile_templating.py
I've added some missing type hints to the tests added by #1027.
=> test: add type hints

copier/main.py, tests/test_updatediff.py
Just like 802d0f96548c3c8a0bf1128f8f18da4cf5ca05ad, but this time we make sure that interactive answers also work as expected.
Basically, I moved the creation of the updated and clean worker after the copying of the real destination worker. With this change, we can ask the user for answers and make sure we use them when producing the clean and updated copy.
@moduon MT-1075
=> fix: properly support diffs over updates with new interactive answers

docs/configuring.md
Just a fix of a minor typo I've stumbled over.
=> docs(configuring): fix typo

.vscode/extensions.json, .vscode/settings.json, copier/main.py, tests/test_symlinks.py
Infinite recursion problem solved.
Fixes https://github.com/copier-org/copier/issues/1091.
=> Fix recursive symlinks

copier/user_data.py, tests/test_output.py
Now that we're more strict in answer types, it's good too to tell more details about what failed.
Now, the type exceptions tell questions, types and answers that failed.
=> fix: explain better why an answer casting fails

copier/tools.py
=> chore: remove unused constant `NO_VALUE`

copier/main.py
I've refactored the implementation of how the answers of the questionnaire are requested and recorded. Before, the questionnaire was implicitly triggered via the impure cached property `Worker(...).answers` which made it difficult to understand when exactly the prompting takes place. For instance, this results in [printing a welcome message _after completing_ instead of _before beginning_ the questionnaire](https://github.com/copier-org/copier/pull/1194#pullrequestreview-1481962789) as this message gets rendered with Jinja where the [render context includes the answers retrieved from the impure property](https://github.com/copier-org/copier/blob/1b351bc8560d19d70e927cdb2fafb4f7ce41092d/copier/main.py#L307) which triggers the prompting.
I've changed the implementation by triggering the …
=> refactor: request answers imperatively instead of implicitly via impure property

copier/tools.py, copier/types.py
Just some minor cleanup. :slightly_smiling_face:
=> style: remove dead code

copier/main.py
=> style: fix typo in error message

copier/cli.py, docs/configuring.md, tests/test_cli.py
re-implements #1059, but adds a test case and uses the current state of `master`.
I'm excited for this feature;  feedback welcome
=> feat: implement reading template data from yaml file

copier/main.py, copier/user_data.py, copier/vcs.py, tests/test_subdirectory.py, tests/test_symlinks.py, tests/test_tmpdir.py, tests/test_vcs.py
Just some polishing :wink:: I've added a couple of missing type hints.
=> build(typing): add missing type hints

docs/updating.md
In this PR, I added docs about two common use cases for updating a project.
=> docs: add uses cases for updating a project

copier/main.py, tests/test_symlinks.py
Previously if an update would try to replace a file with a symlink copier would crash. If an update tried to replace a symlink with a file it would just overwrite the symlink target. Now both cases work as expected.
=> fix: Crash when update replaces file with symlink (or vice versa)

.flake8
=> ci: remove flake8 config file

copier/vcs.py
Just some minor code rewrite to returning early.
=> style: return early

copier/main.py, copier/template.py, copier/user_data.py, copier/vcs.py
I've found a few opportunities for using the beautiful[^1] use of [assignment expressions](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions) (aka Walrus operator) supported by Python 3.8+.
Do we like or dislike this? (+1 for liking :laughing:)
[^1]: apparently [controversial](https://pythonsimplified.com/the-most-controversial-python-walrus-operator/) :shrug:
=> style: use Walrus operator

copier/main.py, tests/test_templated_prompt.py
I've fixed a bug related to handling invalid last answers which caused Copier to raise an exception while updating a project. The solution is to unset a previously recorded answer if parsing or validation fails. For instance, a choice question with choice item validators will fall back to either its default value or the first enabled choice item. In interactive mode without the `--defaults` switch, the user will be given the opportunity to select a valid answer again.
Fixes #1483.
=> fix(updating): unset invalid last answers

copier/main.py, tests/test_tasks.py
Fix https://github.com/copier-org/copier/issues/1598
=> fix(tasks): do not consider unsafe if they are being skipped

.github/workflows/autofix.yml, .github/workflows/ci.yml, README.md
See https://github.com/copier-org/copier/pull/1676#issuecomment-2198051159
=> ci: enable autofix.ci

copier/main.py, copier/tools.py, tests/test_updatediff.py
I've performed an internal change to the update algorithm to avoid creating a subproject copy, which turns out to be a performance regression introduced by #1587.
As of #1587, the update algorithm computes a diff between the _dirty_ HEAD of the subproject's Git repository – dirty because of potentially [staged files during a pre-migration task](https://github.com/copier-org/copier/blob/b7cc803747feae9e8596458c2a2d6c5c75a7b8b2/tests/test_updatediff.py#L1240-L1250) – and a fresh copy based on the old version of the template. Before this PR, a full copy of the subproject directory (excluding the `.git/` directory) was created and the copy was initialized as a new Git repository with one commit comprising all files. For large subprojects, creating a subproject copy incurs non-negligible …
=> perf(updating): avoid creating subproject copy

copier/template.py
Just a minor stylistic refactoring.
=> refactor: set default value for `keep_trailing_newline` more idiomatically

tests/test_updatediff.py
I've added a test case for updating a Git submodule, which was reported to fail in #1805 but turned out to have been fixed as a side effect of #1711. This test will make sure we won't break updating a Git submodule in the future.
This test case fails on the v9.3.1 source tree and passes for the current tip of `master`.
Resolves #1805.
/cc @twsl
=> test: add test case for updating a Git submodule

docs/configuring.md
Closes #2035.
I also added a comment "Refer to example below..." as I accidentally looked at the example and found that it actually contains interesting information about how to use `tasks` variable
=> Improve a bit documentation for `tasks` variable

copier/errors.py
=> use annotations for typing
